# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: components/auth/proto/buckets.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='components/auth/proto/buckets.proto',
  package='components.auth',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n#components/auth/proto/buckets.proto\x12\x0f\x63omponents.auth\"\xb0\x03\n\x06\x42ucket\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x32\n\x03\x61\x63l\x18\x02 \x03(\x0b\x32%.components.auth.Bucket.AccessControl\x1am\n\rAccessControl\x12\x18\n\x10service_hostname\x18\x01 \x01(\t\x12.\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x1e.components.auth.Bucket.Action\x12\x12\n\ngranted_to\x18\x03 \x01(\t\"\xf4\x01\n\x06\x41\x63tion\x12\x1a\n\x16\x42UILDBUCKET_READ_BUILD\x10\x00\x12\x1d\n\x19\x42UILDBUCKET_SEARCH_BUILDS\x10\x01\x12\x1e\n\x1a\x42UILDBUCKET_SCHEDULE_BUILD\x10\x02\x12\x16\n\x12SCHEDULER_READ_JOB\x10\x64\x12\x19\n\x15SCHEDULER_TRIGGER_JOB\x10\x65\x12\x12\n\rLOGDOG_READER\x10\xc8\x01\x12\x12\n\rLOGDOG_WRITER\x10\xc9\x01\x12\x17\n\x12SWARMING_READ_TASK\x10\xac\x02\x12\x1b\n\x16SWARMING_SCHEDULE_TASK\x10\xad\x02\"6\n\nBucketsCfg\x12(\n\x07\x62uckets\x18\x01 \x03(\x0b\x32\x17.components.auth.Bucketb\x06proto3')
)



_BUCKET_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='components.auth.Bucket.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUILDBUCKET_READ_BUILD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUILDBUCKET_SEARCH_BUILDS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUILDBUCKET_SCHEDULE_BUILD', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCHEDULER_READ_JOB', index=3, number=100,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCHEDULER_TRIGGER_JOB', index=4, number=101,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGDOG_READER', index=5, number=200,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGDOG_WRITER', index=6, number=201,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SWARMING_READ_TASK', index=7, number=300,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SWARMING_SCHEDULE_TASK', index=8, number=301,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=245,
  serialized_end=489,
)
_sym_db.RegisterEnumDescriptor(_BUCKET_ACTION)


_BUCKET_ACCESSCONTROL = _descriptor.Descriptor(
  name='AccessControl',
  full_name='components.auth.Bucket.AccessControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_hostname', full_name='components.auth.Bucket.AccessControl.service_hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='components.auth.Bucket.AccessControl.action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='granted_to', full_name='components.auth.Bucket.AccessControl.granted_to', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=242,
)

_BUCKET = _descriptor.Descriptor(
  name='Bucket',
  full_name='components.auth.Bucket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='components.auth.Bucket.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acl', full_name='components.auth.Bucket.acl', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BUCKET_ACCESSCONTROL, ],
  enum_types=[
    _BUCKET_ACTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=489,
)


_BUCKETSCFG = _descriptor.Descriptor(
  name='BucketsCfg',
  full_name='components.auth.BucketsCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buckets', full_name='components.auth.BucketsCfg.buckets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=545,
)

_BUCKET_ACCESSCONTROL.fields_by_name['action'].enum_type = _BUCKET_ACTION
_BUCKET_ACCESSCONTROL.containing_type = _BUCKET
_BUCKET.fields_by_name['acl'].message_type = _BUCKET_ACCESSCONTROL
_BUCKET_ACTION.containing_type = _BUCKET
_BUCKETSCFG.fields_by_name['buckets'].message_type = _BUCKET
DESCRIPTOR.message_types_by_name['Bucket'] = _BUCKET
DESCRIPTOR.message_types_by_name['BucketsCfg'] = _BUCKETSCFG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bucket = _reflection.GeneratedProtocolMessageType('Bucket', (_message.Message,), dict(

  AccessControl = _reflection.GeneratedProtocolMessageType('AccessControl', (_message.Message,), dict(
    DESCRIPTOR = _BUCKET_ACCESSCONTROL,
    __module__ = 'components.auth.proto.buckets_pb2'
    # @@protoc_insertion_point(class_scope:components.auth.Bucket.AccessControl)
    ))
  ,
  DESCRIPTOR = _BUCKET,
  __module__ = 'components.auth.proto.buckets_pb2'
  # @@protoc_insertion_point(class_scope:components.auth.Bucket)
  ))
_sym_db.RegisterMessage(Bucket)
_sym_db.RegisterMessage(Bucket.AccessControl)

BucketsCfg = _reflection.GeneratedProtocolMessageType('BucketsCfg', (_message.Message,), dict(
  DESCRIPTOR = _BUCKETSCFG,
  __module__ = 'components.auth.proto.buckets_pb2'
  # @@protoc_insertion_point(class_scope:components.auth.BucketsCfg)
  ))
_sym_db.RegisterMessage(BucketsCfg)


# @@protoc_insertion_point(module_scope)
