# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tasks_pb2 as tasks__pb2


class TasksStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetTask = channel.unary_unary(
        '/google.devtools.remoteworkers.v1test2.Tasks/GetTask',
        request_serializer=tasks__pb2.GetTaskRequest.SerializeToString,
        response_deserializer=tasks__pb2.Task.FromString,
        )
    self.UpdateTaskResult = channel.unary_unary(
        '/google.devtools.remoteworkers.v1test2.Tasks/UpdateTaskResult',
        request_serializer=tasks__pb2.UpdateTaskResultRequest.SerializeToString,
        response_deserializer=tasks__pb2.TaskResult.FromString,
        )
    self.AddTaskLog = channel.unary_unary(
        '/google.devtools.remoteworkers.v1test2.Tasks/AddTaskLog',
        request_serializer=tasks__pb2.AddTaskLogRequest.SerializeToString,
        response_deserializer=tasks__pb2.AddTaskLogResponse.FromString,
        )


class TasksServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateTaskResult(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddTaskLog(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TasksServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetTask': grpc.unary_unary_rpc_method_handler(
          servicer.GetTask,
          request_deserializer=tasks__pb2.GetTaskRequest.FromString,
          response_serializer=tasks__pb2.Task.SerializeToString,
      ),
      'UpdateTaskResult': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateTaskResult,
          request_deserializer=tasks__pb2.UpdateTaskResultRequest.FromString,
          response_serializer=tasks__pb2.TaskResult.SerializeToString,
      ),
      'AddTaskLog': grpc.unary_unary_rpc_method_handler(
          servicer.AddTaskLog,
          request_deserializer=tasks__pb2.AddTaskLogRequest.FromString,
          response_serializer=tasks__pb2.AddTaskLogResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'google.devtools.remoteworkers.v1test2.Tasks', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
