# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nsjail.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nsjail.proto',
  package='swarming.v1',
  syntax='proto2',
  serialized_options=b'Z-go.chromium.org/luci/swarming/proto/api;apipb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cnsjail.proto\x12\x0bswarming.v1\"S\n\x05IdMap\x12\x11\n\tinside_id\x18\x01 \x01(\t\x12\x12\n\noutside_id\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\r\x12\x14\n\x0cuse_newidmap\x18\x04 \x01(\x08\"\xaf\x02\n\x0cNsJailConfig\x12\x14\n\x0c\x63lone_newnet\x18\x01 \x01(\x08\x12\x15\n\rclone_newuser\x18\x02 \x01(\x08\x12\x13\n\x0b\x63lone_newns\x18\x03 \x01(\x08\x12\x14\n\x0c\x63lone_newpid\x18\x04 \x01(\x08\x12\x14\n\x0c\x63lone_newipc\x18\x05 \x01(\x08\x12\x14\n\x0c\x63lone_newuts\x18\x06 \x01(\x08\x12\x17\n\x0f\x63lone_newcgroup\x18\x07 \x01(\x08\x12\x12\n\nmount_proc\x18\x08 \x01(\x08\x12\"\n\x06uidmap\x18\t \x03(\x0b\x32\x12.swarming.v1.IdMap\x12\"\n\x06gidmap\x18\n \x03(\x0b\x32\x12.swarming.v1.IdMap\x12\x13\n\x0biface_no_lo\x18\x0b \x01(\x08\x12\x11\n\tiface_own\x18\x0c \x03(\tB/Z-go.chromium.org/luci/swarming/proto/api;apipb'
)




_IDMAP = _descriptor.Descriptor(
  name='IdMap',
  full_name='swarming.v1.IdMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inside_id', full_name='swarming.v1.IdMap.inside_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outside_id', full_name='swarming.v1.IdMap.outside_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='swarming.v1.IdMap.count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_newidmap', full_name='swarming.v1.IdMap.use_newidmap', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=112,
)


_NSJAILCONFIG = _descriptor.Descriptor(
  name='NsJailConfig',
  full_name='swarming.v1.NsJailConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clone_newnet', full_name='swarming.v1.NsJailConfig.clone_newnet', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clone_newuser', full_name='swarming.v1.NsJailConfig.clone_newuser', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clone_newns', full_name='swarming.v1.NsJailConfig.clone_newns', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clone_newpid', full_name='swarming.v1.NsJailConfig.clone_newpid', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clone_newipc', full_name='swarming.v1.NsJailConfig.clone_newipc', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clone_newuts', full_name='swarming.v1.NsJailConfig.clone_newuts', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clone_newcgroup', full_name='swarming.v1.NsJailConfig.clone_newcgroup', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mount_proc', full_name='swarming.v1.NsJailConfig.mount_proc', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uidmap', full_name='swarming.v1.NsJailConfig.uidmap', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gidmap', full_name='swarming.v1.NsJailConfig.gidmap', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iface_no_lo', full_name='swarming.v1.NsJailConfig.iface_no_lo', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iface_own', full_name='swarming.v1.NsJailConfig.iface_own', index=11,
      number=12, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=418,
)

_NSJAILCONFIG.fields_by_name['uidmap'].message_type = _IDMAP
_NSJAILCONFIG.fields_by_name['gidmap'].message_type = _IDMAP
DESCRIPTOR.message_types_by_name['IdMap'] = _IDMAP
DESCRIPTOR.message_types_by_name['NsJailConfig'] = _NSJAILCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdMap = _reflection.GeneratedProtocolMessageType('IdMap', (_message.Message,), {
  'DESCRIPTOR' : _IDMAP,
  '__module__' : 'nsjail_pb2'
  # @@protoc_insertion_point(class_scope:swarming.v1.IdMap)
  })
_sym_db.RegisterMessage(IdMap)

NsJailConfig = _reflection.GeneratedProtocolMessageType('NsJailConfig', (_message.Message,), {
  'DESCRIPTOR' : _NSJAILCONFIG,
  '__module__' : 'nsjail_pb2'
  # @@protoc_insertion_point(class_scope:swarming.v1.NsJailConfig)
  })
_sym_db.RegisterMessage(NsJailConfig)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
