
# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: service.proto

import google.protobuf
import access_pb2

from google.protobuf import descriptor_pb2


DiscoveryServiceDescription = descriptor_pb2.ServiceDescriptorProto()
DiscoveryServiceDescription.ParseFromString('0a09446973636f76657279123a0a084465736372696265120f2e646973636f766572792e566f69641a1b2e646973636f766572792e4465736372696265526573706f6e73652200'.decode('hex'))
