#!/usr/bin/env vpython
# Copyright 2021 The LUCI Authors. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

from __future__ import print_function

import json
import os
import re
import tarfile

from six.moves import urllib

BASE_URL = 'https://chromium.googlesource.com/infra/luci/luci-go'
LOG_URL = BASE_URL+'/+log/main/%s?format=JSON&n=1'
TAR_URL = BASE_URL+'/+archive/%s/%s.tar.gz'

SUB_PATHS = [
  'buildbucket/proto',
  'common/proto',
  'resultdb/proto',
]


def main():
    """ ."""
    base_dir = os.path.abspath(os.path.dirname(__file__))
    #base_dir = os.path.join(base, "go.chromium.org/luci/")

    for sub in SUB_PATHS:
        sub_dir = os.path.join(base_dir, os.path.normpath(sub))
        if not os.path.exists(sub_dir):
            os.makedirs(sub_dir)
        os.chdir(sub_dir)

        resp = urllib.request.urlopen(LOG_URL % sub)
        html = resp.read()

        commit = json.loads(html[4:])['log'][0]['commit']
        print('Updating %r to %r' % (sub, commit))

        resp = urllib.request.urlopen(TAR_URL % (commit, sub))
        with tarfile.open(mode='r|*', fileobj=resp) as tar:
            for item in tar:
                if item.name.endswith('.proto'):
                    print('Extracting %r' % item.name)
                    tar.extract(item, '.')
                    print(item.name)
                    with open(item.name, 'r+') as f:
                        text = f.read()
                        text = re.sub('import "go.chromium.org/luci/buildbucket/proto/', 'import "', text)
                        text = re.sub('import "go.chromium.org/luci/common/proto/', 'import "', text)
                        text = re.sub('import "go.chromium.org/luci/resultdb/proto/', 'import "', text)
                        f.seek(0)
                        f.write(text)
                        f.truncate()

        with open('README.md', 'w') as rmd:
            print('// Generated by update_taskbackend_protos.py. DO NOT EDIT.', file=rmd)
            print('// Generated by update_taskbackend_protos.py. DO NOT EDIT.', file=rmd)
            print('These protos were copied from:', file=rmd)
            print(BASE_URL+'/+/'+commit+'/'+sub, file=rmd)


    os.chdir(base_dir)
    os.system("make")
    print('Done.')


if __name__ == '__main__':
    main()
