#!/usr/bin/env vpython
# Copyright 2021 The LUCI Authors. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

from __future__ import print_function

import json
import os
import re
import tarfile

from six.moves import urllib

BASE_URL = 'https://chromium.googlesource.com/infra/luci/luci-go'
LOG_URL = BASE_URL+'/+log/main/%s?format=JSON&n=1'
TAR_URL = BASE_URL+'/+archive/%s/%s.tar.gz'

SUB_PATHS = [
#  'buildbucket/proto',
    'resultdb/proto',
    'common/proto',

]


def main():
    """ ."""
    base = os.path.abspath(os.path.dirname(__file__))
    base_dir = os.path.join(base, "go.chromium.org/luci/")

    proto_paths = []
    for sub in SUB_PATHS:

        sub_dir = os.path.join(base_dir, os.path.normpath(sub))
        if not os.path.exists(sub_dir):
            os.makedirs(sub_dir)
        os.chdir(sub_dir)

        resp = urllib.request.urlopen(LOG_URL % sub)
        html = resp.read()

        commit = json.loads(html[4:])['log'][0]['commit']
        print('Updating %r to %r' % (sub, commit))

        resp = urllib.request.urlopen(TAR_URL % (commit, sub))
        with tarfile.open(mode='r|*', fileobj=resp) as tar:
            for item in tar:
                if item.name.endswith('.proto'):

                    # Add folder path
                    folder = os.path.abspath(os.path.dirname(item.name))
                    if folder not in proto_paths:
                        proto_paths.append(folder)

                    print('Extracting %r' % item.name)
                    tar.extract(item, '.')

        with open('README.md', 'w') as rmd:
            print('// Generated by update_taskbackend_protos.py. DO NOT EDIT.', file=rmd)
            print('// Generated by update_taskbackend_protos.py. DO NOT EDIT.', file=rmd)
            print('These protos were copied from:', file=rmd)
            print(BASE_URL+'/+/'+commit+'/'+sub, file=rmd)


    os.chdir(base)
    proto_paths = [base] + proto_paths
    #proto_paths.append(base)
    os.system("../../../../../components/tools/compile_proto.py . --proto_path %s" % ','.join(proto_paths))
    print('Done.')


if __name__ == '__main__':
    main()
