export const ONGOING_STATES = [
  'PENDING',
  'RUNNING'
];

export const NON_COMPL_EXCEP_STATES = [
  'TIMED_OUT',
  'EXPIRED',
  'NO_RESOURCE',
  'CANCELED',
  'KILLED',
];

export const COUNT_STATES = [
  'COMPLETED_SUCCESS',
  'COMPLETED_FAILURE',
  'PENDING',
  'RUNNING',
  'BOT_DIED',
  'DEDUPED',
  'TIMED_OUT',
  'EXPIRED',
  'NO_RESOURCE',
  'CANCELED',
  'KILLED',
];

export const FILTER_STATES = [
  'ALL',
  'COMPLETED',
  'COMPLETED_SUCCESS',
  'COMPLETED_FAILURE',
  'RUNNING',
  'PENDING',
  'PENDING_RUNNING',
  'BOT_DIED',
  'DEDUPED',
  'TIMED_OUT',
  'EXPIRED',
  'NO_RESOURCE',
  'CANCELED',
  'KILLED',
];
