service: default
runtime: python27
api_version: 1
threadsafe: true

# Approximately 512MB / 2.4GHz
instance_class: F4
automatic_scaling:
  min_idle_instances: 2
  max_concurrent_requests: 20
  min_pending_latency: 50ms
  max_pending_latency: 250ms

default_expiration: "10m"

handlers:
# Cloud Endpoints APIs.
- url: /_ah/api/.*
  script: main_frontend.endpoints_app
  secure: always

- url: /prpc/.*
  script: main_frontend.prpc_app
  secure: always

# Old API URLs.
- url: /api/.*
  script: main_frontend.app
  secure: always

# Static content.
- url: /([^/]+)\.(css|ico|txt)
  static_files: static/\1.\2
  upload: static/(.+)\.(css|ico|txt)
  secure: always
  http_headers:
    Content-Security-Policy: "default-src https: 'self'"
    Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options: deny

# Frontend.
- url: /(user|restricted)(|/.*)
  script: main_frontend.app
  secure: always
  login: required

- url: /newres/(.+)
  static_files: ui2/dist/\1
  upload: ui2/dist/(.+)
  secure: always
  expiration: "1h"
  application_readable: true
  http_headers:
    Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options: deny

# Warning: this includes the bot API at /swarming/api/...
- url: .*
  script: main_frontend.app
  secure: always

builtins:
- remote_api: on

inbound_services:
- mail # This is for 'reply all' to the mail from ereporter2.
- warmup

includes:
- components/auth
- components/config
- components/ereporter2
- components/static_third_party.yaml

libraries:
- name: endpoints
  version: "1.0"
- name: pycrypto
  version: "2.6"
- name: six
  version: "1.9.0"
- name: ssl
  version: "2.7.11"
- name: webapp2
  version: "2.5.2"
- name: webob
  version: "1.2.3"

# Keep this list in sync with service-backend.yaml
skip_files:
# Test and tools.
- (.*/|^)test_support/.*
- .*/test/.*
- .+_test\.py$
- ^tool_support/
- ^tools/
- support/
- test.py$
- test_.+
# Junk files.
- ^(.*/)?\..*
- .+\.orig$
- .+\.rej$
- .+\.zip$
- ^(.*/)?#.*#
- .+~
- .+\.py[co]
# Doc, readme and license.
- ^doc/
- ^[A-Z]+$
- ^[A-Z]+\.[a-z]+$
- ui2/node_modules/.+
- ui2/modules/.+
- ui2/nodejs/.+
- ui2/pages/.+
