# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import tasks_pb2 as tasks__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='plugin.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cplugin.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0btasks.proto\"q\n\x12\x41ssignTasksRequest\x12\x14\n\x0cscheduler_id\x18\x01 \x01(\t\x12\x1b\n\tidle_bots\x18\x02 \x03(\x0b\x32\x08.IdleBot\x12(\n\x04time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"3\n\x07IdleBot\x12\x14\n\x0cscheduler_id\x18\x01 \x01(\t\x12\x12\n\ndimensions\x18\x02 \x03(\t\";\n\x13\x41ssignTasksResponse\x12$\n\x0b\x61ssignments\x18\x01 \x03(\x0b\x32\x0f.TaskAssignment\"1\n\x0eTaskAssignment\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\"/\n\x17GetCancellationsRequest\x12\x14\n\x0cscheduler_id\x18\x01 \x01(\t\"\x8a\x01\n\x18GetCancellationsResponse\x12=\n\rcancellations\x18\x01 \x03(\x0b\x32&.GetCancellationsResponse.Cancellation\x1a/\n\x0c\x43\x61ncellation\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\"T\n\x0fNotifyTasksItem\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x04task\x18\x02 \x01(\x0b\x32\t.TaskSpec\"S\n\x12NotifyTasksRequest\x12\x14\n\x0cscheduler_id\x18\x01 \x01(\t\x12\'\n\rnotifications\x18\x02 \x03(\x0b\x32\x10.NotifyTasksItem\"\x15\n\x13NotifyTasksResponse2\xd0\x01\n\x11\x45xternalScheduler\x12\x38\n\x0b\x41ssignTasks\x12\x13.AssignTasksRequest\x1a\x14.AssignTasksResponse\x12G\n\x10GetCancellations\x12\x18.GetCancellationsRequest\x1a\x19.GetCancellationsResponse\x12\x38\n\x0bNotifyTasks\x12\x13.NotifyTasksRequest\x1a\x14.NotifyTasksResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,tasks__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ASSIGNTASKSREQUEST = _descriptor.Descriptor(
  name='AssignTasksRequest',
  full_name='AssignTasksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scheduler_id', full_name='AssignTasksRequest.scheduler_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='idle_bots', full_name='AssignTasksRequest.idle_bots', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='AssignTasksRequest.time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=175,
)


_IDLEBOT = _descriptor.Descriptor(
  name='IdleBot',
  full_name='IdleBot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scheduler_id', full_name='IdleBot.scheduler_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dimensions', full_name='IdleBot.dimensions', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=228,
)


_ASSIGNTASKSRESPONSE = _descriptor.Descriptor(
  name='AssignTasksResponse',
  full_name='AssignTasksResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='assignments', full_name='AssignTasksResponse.assignments', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=289,
)


_TASKASSIGNMENT = _descriptor.Descriptor(
  name='TaskAssignment',
  full_name='TaskAssignment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bot_id', full_name='TaskAssignment.bot_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='TaskAssignment.task_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=340,
)


_GETCANCELLATIONSREQUEST = _descriptor.Descriptor(
  name='GetCancellationsRequest',
  full_name='GetCancellationsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scheduler_id', full_name='GetCancellationsRequest.scheduler_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=389,
)


_GETCANCELLATIONSRESPONSE_CANCELLATION = _descriptor.Descriptor(
  name='Cancellation',
  full_name='GetCancellationsResponse.Cancellation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bot_id', full_name='GetCancellationsResponse.Cancellation.bot_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='GetCancellationsResponse.Cancellation.task_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=530,
)

_GETCANCELLATIONSRESPONSE = _descriptor.Descriptor(
  name='GetCancellationsResponse',
  full_name='GetCancellationsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cancellations', full_name='GetCancellationsResponse.cancellations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GETCANCELLATIONSRESPONSE_CANCELLATION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=530,
)


_NOTIFYTASKSITEM = _descriptor.Descriptor(
  name='NotifyTasksItem',
  full_name='NotifyTasksItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='NotifyTasksItem.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task', full_name='NotifyTasksItem.task', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=616,
)


_NOTIFYTASKSREQUEST = _descriptor.Descriptor(
  name='NotifyTasksRequest',
  full_name='NotifyTasksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scheduler_id', full_name='NotifyTasksRequest.scheduler_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notifications', full_name='NotifyTasksRequest.notifications', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=701,
)


_NOTIFYTASKSRESPONSE = _descriptor.Descriptor(
  name='NotifyTasksResponse',
  full_name='NotifyTasksResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=703,
  serialized_end=724,
)

_ASSIGNTASKSREQUEST.fields_by_name['idle_bots'].message_type = _IDLEBOT
_ASSIGNTASKSREQUEST.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ASSIGNTASKSRESPONSE.fields_by_name['assignments'].message_type = _TASKASSIGNMENT
_GETCANCELLATIONSRESPONSE_CANCELLATION.containing_type = _GETCANCELLATIONSRESPONSE
_GETCANCELLATIONSRESPONSE.fields_by_name['cancellations'].message_type = _GETCANCELLATIONSRESPONSE_CANCELLATION
_NOTIFYTASKSITEM.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_NOTIFYTASKSITEM.fields_by_name['task'].message_type = tasks__pb2._TASKSPEC
_NOTIFYTASKSREQUEST.fields_by_name['notifications'].message_type = _NOTIFYTASKSITEM
DESCRIPTOR.message_types_by_name['AssignTasksRequest'] = _ASSIGNTASKSREQUEST
DESCRIPTOR.message_types_by_name['IdleBot'] = _IDLEBOT
DESCRIPTOR.message_types_by_name['AssignTasksResponse'] = _ASSIGNTASKSRESPONSE
DESCRIPTOR.message_types_by_name['TaskAssignment'] = _TASKASSIGNMENT
DESCRIPTOR.message_types_by_name['GetCancellationsRequest'] = _GETCANCELLATIONSREQUEST
DESCRIPTOR.message_types_by_name['GetCancellationsResponse'] = _GETCANCELLATIONSRESPONSE
DESCRIPTOR.message_types_by_name['NotifyTasksItem'] = _NOTIFYTASKSITEM
DESCRIPTOR.message_types_by_name['NotifyTasksRequest'] = _NOTIFYTASKSREQUEST
DESCRIPTOR.message_types_by_name['NotifyTasksResponse'] = _NOTIFYTASKSRESPONSE

AssignTasksRequest = _reflection.GeneratedProtocolMessageType('AssignTasksRequest', (_message.Message,), dict(
  DESCRIPTOR = _ASSIGNTASKSREQUEST,
  __module__ = 'plugin_pb2'
  # @@protoc_insertion_point(class_scope:AssignTasksRequest)
  ))
_sym_db.RegisterMessage(AssignTasksRequest)

IdleBot = _reflection.GeneratedProtocolMessageType('IdleBot', (_message.Message,), dict(
  DESCRIPTOR = _IDLEBOT,
  __module__ = 'plugin_pb2'
  # @@protoc_insertion_point(class_scope:IdleBot)
  ))
_sym_db.RegisterMessage(IdleBot)

AssignTasksResponse = _reflection.GeneratedProtocolMessageType('AssignTasksResponse', (_message.Message,), dict(
  DESCRIPTOR = _ASSIGNTASKSRESPONSE,
  __module__ = 'plugin_pb2'
  # @@protoc_insertion_point(class_scope:AssignTasksResponse)
  ))
_sym_db.RegisterMessage(AssignTasksResponse)

TaskAssignment = _reflection.GeneratedProtocolMessageType('TaskAssignment', (_message.Message,), dict(
  DESCRIPTOR = _TASKASSIGNMENT,
  __module__ = 'plugin_pb2'
  # @@protoc_insertion_point(class_scope:TaskAssignment)
  ))
_sym_db.RegisterMessage(TaskAssignment)

GetCancellationsRequest = _reflection.GeneratedProtocolMessageType('GetCancellationsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCANCELLATIONSREQUEST,
  __module__ = 'plugin_pb2'
  # @@protoc_insertion_point(class_scope:GetCancellationsRequest)
  ))
_sym_db.RegisterMessage(GetCancellationsRequest)

GetCancellationsResponse = _reflection.GeneratedProtocolMessageType('GetCancellationsResponse', (_message.Message,), dict(

  Cancellation = _reflection.GeneratedProtocolMessageType('Cancellation', (_message.Message,), dict(
    DESCRIPTOR = _GETCANCELLATIONSRESPONSE_CANCELLATION,
    __module__ = 'plugin_pb2'
    # @@protoc_insertion_point(class_scope:GetCancellationsResponse.Cancellation)
    ))
  ,
  DESCRIPTOR = _GETCANCELLATIONSRESPONSE,
  __module__ = 'plugin_pb2'
  # @@protoc_insertion_point(class_scope:GetCancellationsResponse)
  ))
_sym_db.RegisterMessage(GetCancellationsResponse)
_sym_db.RegisterMessage(GetCancellationsResponse.Cancellation)

NotifyTasksItem = _reflection.GeneratedProtocolMessageType('NotifyTasksItem', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYTASKSITEM,
  __module__ = 'plugin_pb2'
  # @@protoc_insertion_point(class_scope:NotifyTasksItem)
  ))
_sym_db.RegisterMessage(NotifyTasksItem)

NotifyTasksRequest = _reflection.GeneratedProtocolMessageType('NotifyTasksRequest', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYTASKSREQUEST,
  __module__ = 'plugin_pb2'
  # @@protoc_insertion_point(class_scope:NotifyTasksRequest)
  ))
_sym_db.RegisterMessage(NotifyTasksRequest)

NotifyTasksResponse = _reflection.GeneratedProtocolMessageType('NotifyTasksResponse', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYTASKSRESPONSE,
  __module__ = 'plugin_pb2'
  # @@protoc_insertion_point(class_scope:NotifyTasksResponse)
  ))
_sym_db.RegisterMessage(NotifyTasksResponse)


# @@protoc_insertion_point(module_scope)
