# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: swarming.proto

import base64
import zlib

from google.protobuf import descriptor_pb2

# Includes description of the swarming.proto and all of its transitive
# dependencies. Includes source code info.
FILE_DESCRIPTOR_SET = descriptor_pb2.FileDescriptorSet()
FILE_DESCRIPTOR_SET.ParseFromString(zlib.decompress(base64.b64decode(
    'eJylV01vG8kRNWlJpkey06bhzVoxgoYP6/3QkracBXZtwIgscReMZUmQqGAPCZjmTJNsaKZ70t'
    '0jWrc9J0CA/Icgh/yDXHLIMZccAuSUWw75A7nkllc9Q3Lo9R6CAIbMrqmuqXr16nVP9JsfRrfd'
    'TNhM6Uknt8abdmu+ftiO2Evje5dSe3cqf1lI5x/eje7UbC432smPf9+Ibg6Euzjzwsv2/ejeYO'
    '/s1dlgb9Abnh+dnfT2+1/2ewfsWnszunF6fnTUP/qKMVqc9I4OaMFp0fv6pH8Kt8ftWwjXf907'
    'GB6fD9iP21tR6+XxYHhAMU5otb93tN87xOoX5Lp//PrksDfAMkeYjVf9Q3r0TaPNos2j4+Fp7+'
    'z4/HS/x75p7kZR66yq7ie/fhC12Ca7xl6zRvSPtdZWWLR3/9Dg+ya/smoy9Xz38ZPP+WAq+eH5'
    'fp/vFX5qrOvwvTTlwcFxK520lzLpRPzcSW7G3E+V484UNpY8NonkWE7MpbRaJrzQibRwkXwvFz'
    'EFVrEEhjv8p9I6ZTTf7TyO4CA8j4XmI8nHBpu40mHXYX+/d3TW42OVyk60+7vryA7xQ+u4t0o6'
    'jh+x0XjfRPKZ8tOIT73P3bNud4JVMerEJutOjJmkUuTK1X+OUjPqZsJ5aStzN5GX3pjUda3MjJ'
    'czYy+QaPfyiQcddrsRF45nRTyl/5WnWh3qUaNUUiIfauPD4486vO/5VNBjpCZSFDSVFjTiiQq5'
    '6li6EG3eoeAtyuAzRbAVADgW+CMASPk0UeNxGWYMlESGX4idAfY0AnKWj5CAI152VgMTmKnKFB'
    '4R6ugbpeqKPDfWk1M8VWmCyBEHBGiSe8bDGx0eojiKq2pr+UbGRQhVaOV38DdVF5Kfvux1wLpW'
    'k91iLcaiV62N1jV2B0y7yxoPP+OD44PjDzNhC5l+9Ix/qbRyU66yPJWhFArYWfTviydPv/jsab'
    'S7wfdO+gi7RcFaDYSj0FutNYS+h9DvgdFhhWf38Oz9sGqw9/HsfvWsEdYtdj/6baO1jo28HIVt'
    'wxejDHLnxG/MesBrCbZIUzMDnQOyLgAtwj5kVTIS/7y4kJqPrcn4XFOGNo9dJ796tnhHtNsOG7'
    'nDNCRFSkJEla2H7DlbZ7ejnbBqIsmHrMkebD/gfX0pUlW9f4cnJnQP/MBeNvfGfvL/fs3ShGWb'
    '/SD6W6MyNdgHcLmz/edGGHNPmSD1uLBUZ3rFbaE15bSoCoM4FrHnT3kOHhEtCBo0zisBztGgT6'
    'VIiP1j6cFdpfPCh4F1O8EXuwuQNLyrCr8TKE0PvRQW9cz0aihhwcdL6EvhF9HITluCANla5Y2q'
    'rJs1SxOWLbDkV83K1GSfhMr/812V51Iny8ozKbQrdUmbwH4LzZBV0tR5DHiEQYU0oitXpWCRHA'
    'QmFdqrlEsIkCSqlLUjQBANUyqifJMrGygfcZniGVR1mVuVTs0riE0uYzVWyENAPQKrUgxrZ+k1'
    'dDIG8EZLhLBlLBd8loARDz5ZAazEhwD795wq11k3APbPVcCIePPchL7KjJVlNzUJHbcQ8aQIYp'
    'iK+IKEJhaQfuWvOtG3oDUBnymOFvyXW2Us/MKrXIikNLQZjCjZEnrhudSmmEDm0RTHZxhQLi6F'
    'SkWlwaBY2YmQMY3qd8IEKuHoSFwNmuuAprsCzXVA013l0hr7EVzurnCJ0qWXpUZPwpEnyhNsLh'
    '1eZTQ2ZdNOrEFzPI6vzkJIh+QBvpeZVWnXHJVZ8XgbzVKikUEsx0UKPl+AmjW+0pkJVXek6ol0'
    'sVUjOT9mIz6xIuzDPJJwlXxLBA6p+UmcmLhYavQSMBJaQmOzZmnCcpu1o3/NubTOPodLe/vvbw'
    'E2wmzPU5+GPuN1SEFDL8boaUHkKrTFeHiZzAWAtkcYJCfTcThnq5tDxbulRsBINC30CkEm0pcZ'
    'FHlCchqFHVPjwEfNZ1MFEZsnBYAryeKxFW5KP9AaK0fG+CBk0LwaGutAg0qtW5qw3GJ3orSybL'
    'DnAYyfLbFYzE45SjO6ZAgN1UQfY+pCaOWlEiGxR6XpER2LKBE9lwRH2FaqVC2jDWT0fCWjDWT0'
    'PGSUVZYb7EXg889Xu0Op4PKEw5nA18ZmlFBdoypKyTd4e7j7ZVBCdOIxQMLlRpfzjbOrqMvPDa'
    'T0YoUyN5DSi0CZv8wp02Iv4cK2//gOyqzgU/H8XeC8peUy+j9mZDEi0f8+Iy0UTNW0apYmLJvs'
    'e9Ff1yrTTXYIl/e2/7S2LJgKLbnhiLSGV18QC5aoLJOJAovp6EZ2OEN2uKiKrYYgkWXCstJQ6o'
    'kspTzgMdfnb4lnCR/u0yKH4js0NhZ0J632QUwNLgR0JywgUpRh+Byge1T4eqIXUhUJZEvTZZ+E'
    'lp/Bb6nIM6H8EB0Z1rMY2HKSQ6fq8wzbhZR5Wd7yaFselvhQW5zEdHXu8K+kpvs38MHZKS7CzC'
    '76Tcd3FHb5kkwOXxA0/oZXn2dzNK18tACswkl5AgiAOqGSndIJpAe2TiEccQDnUwl2UJILjXtO'
    '2QPk6ExGUPpP8b3xaaJwbwi3el/QgUaZJSVdwxWDOiBsuTcYMGTvPPBqrLsJ1hGlbtUsTVgYuz'
    'faCF9QT/8LRnRz9g==')))
_INDEX = {
    f.name: {
      'descriptor': f,
      'services': {s.name: s for s in f.service},
    }
    for f in FILE_DESCRIPTOR_SET.file
}


SwarmingServiceDescription = {
  'file_descriptor_set': FILE_DESCRIPTOR_SET,
  'file_descriptor': _INDEX[u'swarming.proto']['descriptor'],
  'service_descriptor': _INDEX[u'swarming.proto']['services'][u'Swarming'],
}
