# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: swarming.proto

import base64
import zlib

from google.protobuf import descriptor_pb2

# Includes description of the swarming.proto and all of its transitive
# dependencies. Includes source code info.
FILE_DESCRIPTOR_SET = descriptor_pb2.FileDescriptorSet()
FILE_DESCRIPTOR_SET.ParseFromString(zlib.decompress(base64.b64decode(
    'eJylV8+PG0kVjj0/4qn8oOKwS+JEopQVCguznqz3AAqraJ2Jd2V2dmY0PxAH0FDuLtulaVc1Vd'
    'XjzG3P3BD/AuLAf8CFAyfEhQMSJ24c+Ae4cON71W27nc0eEFI0cb1+Vf3e9773vWr2m2+zu34u'
    '3UybSTd3Nth2a7F+0mb8pQ2DK2WCP1G/LJQPT+6zezWbz63x6nu/a7CdM+kvT4MMqv2QvXPWP/'
    '389Kx/Nrg4Pzw9HuwPPx0OXvEb7Vvs5sn54eHw8DPOaXE8OHxFC0GLwU+Phydwe9a+g+OGXwxe'
    'XRydn/FP2rdZ6+XR2cUrOuOYVvv9w/3BAVa/INf9oy+ODwZnWOY4Zvvz4QE9+rLR5uzW4dHFye'
    'D06Pxkf8C/bPZOWOu0yq79KdtZZtLudJcovJly59Fbn5WpP7nx4z8/Zi1+i9/gx7zB/rHZuh0X'
    '7d7vG2Lf5tdOT6ZB9J59+ENxNlXi4Hx/KPpFmFrnu6KfZSI6eOGUV+5KpV0mzr0SdizCVHvhbe'
    'ESJRKbKoHlxF4pZ1QqCpMqBxcl+rlM6GCdKAS0K36inNfWiF73GYODDCKRRoyUGFtsEtrEXQfD'
    '/cHh6UCMdaa6rPfbDUSH8yMFRHBaeYEfiTV430SJuQ5TJqYh5P753t4Eq2LUTexsb2LtJFMy17'
    '7+c5TZ0d5M+qBcZd5L1VWwNvN7Ts1sUHPrLhHo3tWHARj39piQXsyKZEr/60C5euSjR5miQL5r'
    'bIiP3++KYRBTSY8RmsyQ0FQ51ESkOsZqEuXjaYtKR29ZHj7XBFsBgBOJPxKAlE9TPR6Xx4yBkp'
    'zhF86eAfaMATknRgjAE7+76wcTmJmeaTwi1FE3CtUXeW5dIKdkqrMUJzMBCFAk/1zEN3o8RHJ0'
    'rq6t1WuVFPGowuiwi7+ZvlTi5OWgy1ir1eR3eItz9s3WdusGvwemvcsbvW3RPx7i+W2ythqwk8'
    '/HcdWE333e5J90dsWSv6BbKJzxQi2WmYzRAmtE5HEWX+zGeff5Nv9GzdKEhXNRs2zA8n3+MSLY'
    'xPseIK6HaIe4wv4HiOdBXDX4Izx7XD1rxHWLP2S/brS2sPG9so86Viz1BLHl1BwUJoG9qpTMMj'
    'tHL8Sy+FglGfch+pLO+BfkpTJi7OxMLNr4wuWJ7+bXz5fvYL123Cg8WiktMup1QnMrRv8e3+J3'
    '2W5cEZrfAZqPO4/F0FzJTFfv3xWpjaUHuSJ6W0v0yP9bNUsTlg5/xP7WqEwN/j5c7nX+1IgaES'
    'gShJ4UjvLMroUrjKGYllmhi8cyCeIjkYOExCmCRoMxWoKwpBJTJVMq51gFEF+bvAix2/1u9MXu'
    'AgyP76qO3439QA+Dkg75zM36UdKBzFcQpyIsTyM7bYnq5WqZN6q0dmqWJiy3wcxfNStTk3dj5v'
    '/5usxzZdJV5jMljS9FzUSighwyV1XQVHmoA0OXQ1dRletS7UhLIpMKE3QmFNRLEVXK3HFAVBxb'
    'yql6nWsXe5kJNEXuIcmr2Kpwal5RqXKV6LFGHBLSE1mVodO7K68LrxIAb43CEa48y0efFWDEg+'
    '4aYCU+BNi/F1TZ4L0I2D/XASPiLWKT5npmnSqraUglhcMESIuopJlMLkmlEom5ocN1l30FWhvx'
    'mWIu4b/caevgF1/l40naQNjBiJItsRZBKGOLCWYEqYeYo0GFvJI6k5WAg2JlJWLE1KpfCxOohL'
    'mT+ho0G4CmtwbNBqDprXNpk/8ALvfXuETh0ssyayZxXspy/C2kI+gZtU1ZtGNnUZyA2dddqvAF'
    'eYDvZWRV2DVHbdc83kSz1HdEkKhxkYHPl6Bmja80cDESPI2EVPnE6ZFazGgmJk7GfehHEq6Sb6'
    'nEhFuM8dQmRZxV9KgGGAktoXGrZmnCcpe32b8WXNriP4JLu/P3NwAbobcXoU9jnfE6hGCgF2PU'
    'tCByFSbODJUuBIC2MzSSV9k4Dunq2lHxbqURMBJNC7NGkIkKZQRFnpKcsrhjaj34aMR8qiFii6'
    'AAcCVZInHST+kHSuPUyNoQhQyaV0NjC2hQqnVLE5Y7/B7LKss2fxHB+NkKi2XvlK00pxuKNFBN'
    '1DGhKsRSXmkZA3tamp7SKEaKqLkiOOK2UqVqEW0johdrEW0johcxolllucn7kc8/X68OhYKbV5'
    '4pAt9YN6OA6hpVUUq9xtvjxXEGJUQlngEk3IxM2d+YXUVdfm4ipP4aZW4ipH6kzF8WlGnxAVx4'
    '5w9vocwaPhXP3wbOG1qu2P/RI8sWYf97j7SQMGXTqlmasNzCVeevm5Vphx/B5d3OHzdXCVOiJT'
    'c8kdaK6jNmyRI9m6lUg8U0uhEdZsiukFWyVROkqgxYVRpKNVGllEc8Fvr8FfEs4cNlXOZQfI/C'
    'JpIutNU+iKnFhYAulAVEiiKM3xJ0j4rfM/RCyiKFbBn6UiChFafwWynyXOpwgYpc1KM4c2Unx0'
    'rV+xm2S6XyMr3VaFsNS9wxl5OY7t1d8ZkydHkHPpid8jL27LLeNL5ZeTMtyeTx+UHtb0X1jbhA'
    '06mnS8AqnHQggAColzrdLZ1AemDrNY4jDmA+lWBHJbk0uOeUNUCM3s4IyvABPlY+SDXuDfGTAJ'
    'dlDA2KLC3pGq8YVAHpyr3RgCZ768CrsW4HrCNK3alZmrBw/s5oO35+ffRfGOOQWA==')))
_INDEX = {
    f.name: {
      'descriptor': f,
      'services': {s.name: s for s in f.service},
    }
    for f in FILE_DESCRIPTOR_SET.file
}


SwarmingServiceDescription = {
  'file_descriptor_set': FILE_DESCRIPTOR_SET,
  'file_descriptor': _INDEX[u'swarming.proto']['descriptor'],
  'service_descriptor': _INDEX[u'swarming.proto']['services'][u'Swarming'],
}
