# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/notifications/notifications.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from proto.api_v2 import swarming_pb2 as proto_dot_api__v2_dot_swarming__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/notifications/notifications.proto',
  package='swarming.notifications.tasks',
  syntax='proto3',
  serialized_options=b'ZBgo.chromium.org/luci/swarming/server/notifications/taskspb;taskspb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'proto/notifications/notifications.proto\x12\x1cswarming.notifications.tasks\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bproto/api_v2/swarming.proto\"\xbd\x01\n\x10PubSubNotifyTask\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x12\n\nauth_token\x18\x03 \x01(\t\x12\x10\n\x08userdata\x18\x04 \x01(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12%\n\x05state\x18\x06 \x01(\x0e\x32\x16.swarming.v2.TaskState\x12.\n\nstart_time\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"b\n\x15\x42uildbucketNotifyTask\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12%\n\x05state\x18\x02 \x01(\x0e\x32\x16.swarming.v2.TaskState\x12\x11\n\tupdate_id\x18\x03 \x01(\x03\x42\x44ZBgo.chromium.org/luci/swarming/server/notifications/taskspb;taskspbb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,proto_dot_api__v2_dot_swarming__pb2.DESCRIPTOR,])




_PUBSUBNOTIFYTASK = _descriptor.Descriptor(
  name='PubSubNotifyTask',
  full_name='swarming.notifications.tasks.PubSubNotifyTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='swarming.notifications.tasks.PubSubNotifyTask.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topic', full_name='swarming.notifications.tasks.PubSubNotifyTask.topic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auth_token', full_name='swarming.notifications.tasks.PubSubNotifyTask.auth_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userdata', full_name='swarming.notifications.tasks.PubSubNotifyTask.userdata', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tags', full_name='swarming.notifications.tasks.PubSubNotifyTask.tags', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='swarming.notifications.tasks.PubSubNotifyTask.state', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='swarming.notifications.tasks.PubSubNotifyTask.start_time', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=325,
)


_BUILDBUCKETNOTIFYTASK = _descriptor.Descriptor(
  name='BuildbucketNotifyTask',
  full_name='swarming.notifications.tasks.BuildbucketNotifyTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='swarming.notifications.tasks.BuildbucketNotifyTask.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='swarming.notifications.tasks.BuildbucketNotifyTask.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_id', full_name='swarming.notifications.tasks.BuildbucketNotifyTask.update_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=425,
)

_PUBSUBNOTIFYTASK.fields_by_name['state'].enum_type = proto_dot_api__v2_dot_swarming__pb2._TASKSTATE
_PUBSUBNOTIFYTASK.fields_by_name['start_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_BUILDBUCKETNOTIFYTASK.fields_by_name['state'].enum_type = proto_dot_api__v2_dot_swarming__pb2._TASKSTATE
DESCRIPTOR.message_types_by_name['PubSubNotifyTask'] = _PUBSUBNOTIFYTASK
DESCRIPTOR.message_types_by_name['BuildbucketNotifyTask'] = _BUILDBUCKETNOTIFYTASK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PubSubNotifyTask = _reflection.GeneratedProtocolMessageType('PubSubNotifyTask', (_message.Message,), {
  'DESCRIPTOR' : _PUBSUBNOTIFYTASK,
  '__module__' : 'proto.notifications.notifications_pb2'
  # @@protoc_insertion_point(class_scope:swarming.notifications.tasks.PubSubNotifyTask)
  })
_sym_db.RegisterMessage(PubSubNotifyTask)

BuildbucketNotifyTask = _reflection.GeneratedProtocolMessageType('BuildbucketNotifyTask', (_message.Message,), {
  'DESCRIPTOR' : _BUILDBUCKETNOTIFYTASK,
  '__module__' : 'proto.notifications.notifications_pb2'
  # @@protoc_insertion_point(class_scope:swarming.notifications.tasks.BuildbucketNotifyTask)
  })
_sym_db.RegisterMessage(BuildbucketNotifyTask)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
