# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: isolated.proto

import base64
import zlib

from google.protobuf import descriptor_pb2

# Includes description of the isolated.proto and all of its transitive
# dependencies. Includes source code info.
FILE_DESCRIPTOR_SET = descriptor_pb2.FileDescriptorSet()
FILE_DESCRIPTOR_SET.ParseFromString(zlib.decompress(base64.b64decode(
    'eJylWs1zE0mWpyxsi8JAIT7aY+jubLuNLZBK8gcwmN6DLMt20bLk0QcMEB1QklJ2DVKVVlWyMS'
    'zbp93jxv4HE7GHPcx9976njYmY8/4Fe9jY2972uL+XmVUqGxgmeh0Gsn6Z7zNfvveyCv1/fqVf'
    'dnyvZwe8Yw6GXuClkuHz3LcHnnfQ4zmBt0bdXOD0uR/Y/YFcOv+Pmj5TD+zAr/G/HmEmtapPEa'
    'kfzGpMW764OmdKFmbIwmyELGpqZWpd14ccIkeB47mzE6C7vHrdjJSqRXO12LrUTX3KHfVbfDib'
    'AMVkTT3Nv9UvKY38gef6/BeptKbP9Lntj4a8z93Ah1IJUF4ZKyVFnFo0/8cJfVLgqbv6BIi+LA'
    '6rUrP69GjQ8+yOL0xP1MLH1IJ+SQ1ftU6gljA0UZtR4CZhqdv6hY537EoG58WCMZBa0q9ED4rJ'
    'pFhzOYIlm3v61bbnBrbj+q+Gci/92Smx1Agn1B77qbQeYa96nvdmNPBnp8XaKyFelnBqTk9G7J'
    'JiSfRMc13b6cF//uwFORc+393U9fG+py7q01blaaFsbRnnUro+tWdVmo2SoaWS+vndarNmTKSm'
    '9cRW4bmRIOhZqfSjcX61pE/X+fDIafPURrgzN89uoVRm7quPcBk98+ee/Ps1PWmcN84ZG4am/4'
    'uWnBEPqdU/aKzoDU6GzsFhwFbzK79mjUPOys2ixQqj4NAb+iYr9HpMLPAZrIIy4K+zps+Z12XB'
    'oeMz3xsN25y1vQ5neDzwjvjQ5R02cjt8iCWcFQZ2mxjDDiiUYU/50IdT2KqZ17HADljbdlmLs6'
    '4HIua4gqpsFUuVeol1HYSerieTE8aUkTQMDBPJcxhNG8v6THIKYx3mXIJt4imp4TlpXNFfiqcJ'
    'zM8YE8b63I9MOAZ2BKOhC8Xx5PiB0/YheCiNofTAhrZ7wBnUIjXUZsOg8dGFOkbIHOJmoNjFGD'
    'IBZMaYjSEJPC8Yef2H5CTUMaDuTUObM9k4QljgsZHPhSZqz81QXaEAZM4QNeQZxiTMuyyeyLyr'
    'MO8ypE1GGhFyIYZMAJkxLkU0mpHCikvRCk0hyRgyAeSiMRPRTBjXsOJitIK4EDIVQ2jNBexQSJ'
    'MwrmOFHq1IgIaQyRgyASQJbUOa88aNU3LOg+bGKTnnQXNDyJnB+JwxC38ysf3nhfWz4HddH4kn'
    '8s8tUC/NcSZTIwUpbWzPxhhpb3hCvkf0+QPedroOjyIw9Dyzusz1gvGCjB7y6vCuPephl8DC9Y'
    '6xSalQLAwhwbPGTSgeYlMCuxVDNCC3jfkYkgCyaNzRlxSiGV+D5vbcV6z26VgMRWoQSUtvGUsR'
    'Ow0iCZuJIcTwkvFVDEkAmYNaGYVMGN+C5trcbVYRNYkOu4xG2CnPT0wu7Rmt/9q4HfGcSE4KbD'
    'qGaECSIlJDJAHkqpESO6cZ89jHJbWPmnhOGjcQF/RE+7hA+yikasrBhMwrSzTl4IXIwZpy8ELk'
    'YE05eEE4+I1CNOMO8Zl7qWwUQZERUUDpwBsikTnugfnZADIpcQ55mMYOvR739TCKeo44vKF42q'
    'Q76lCEyBSQi4YRQ0ilq8bXMSQBhBnf6asi/O/KbD73vVI5rFrMl7kjltxMeUzIzLtw6CXh0Anh'
    '0HvQY0E4dEI5lJC7SC5GhE0J7FYM0YDcNr6JIQkg38HFIWfNyILmesSZbCbkHqQZETYpsOkYQn'
    'TJmHSyOos0dC3iPGGYoJmLOFPoEZKFNCPCJgU2HUM0IBRMYyQBZNb4VcQ5YeRAczPinABnQkxI'
    'MyJsUmDTMUQDkjSuxhDidF0FrtQwT+c34nxeITmVGSQ2KbDpGKIBSarglkgCCB3TukImjTXQfD'
    'NXjB3TXBQKYZvCbBTVwAvsHnOjZU7A+z6j3odK9UCdZsEU6hHbvDrNEpOipmOIBiQJB46RBJDb'
    'CNrQ8CljnbJCxHkKnAlZiwXPFDivn+I8Bc7r4DwbQxJAkCb1xwqZNh6C5sbcPdY4Y1dkNBJV2+'
    '61R3Rm2W/262MDp6EGka+r8yWxSYFNxxANSFKdSokkgFxDpGUVkjQeCTW+jvnf9dzsaj4fKRLz'
    'bBKCieBhLBCTEPzolOAkBD86JTgJwY9IcGtKtOBr+n/m9C/dbFJXznTt84/1C1HjTk27zxEqHd'
    'nlo2lXj6nr+qRru55s5idr8mHzb/Vrba9/9iaweTniuE/Qvvbi3oETHI5aJlbnDtCQugdjFQfB'
    'yYD7Y03/V9P+aSKxs7/5h4lvdiTn/fCO8Yz3ej+ipLoNonny31n9gvENst7fa6gQf5pBE/uNaG'
    'L/bYYJmrbXY5ujbhe9JcsyyW3JZx07sJGJAz5sH4q2Dg1W3w70U51v/teKgFlu22SfaXoPg2Dg'
    'b+RyHX7Ee94AgkJ3kK0DpUS2JZXI6TrqdQc5eOi0ZItH55B6PBQG1TQT0nJcGz0I6eVn2DG8h4'
    'oj/vVG0LPvddBztG3ikGE2qgwk952AugDIPHI6GIgmmopN1+v1vGMUK6oIHYeIfCICHx5sQCX6'
    'uXtGMZ/iNt7G90eobCjztiphdgtNPaaUx3TqhlBkMrJnpgJHHOISKeOcUgfy2j0bGz80P6cEhM'
    'V8ESoBGzsjKBbpoY8V+X/pERXojtce0f3XDjcpB/97mBkyRApKv93zx64WG4RJncW1j4yqcEdQ'
    'EmPX7otrUjy2XG8858tE7OuifAtWuHNB6Al1EYgUStvoMDpAqQ0hJfoe0pn0CaKTGhMEJ+tiQg'
    '+vY93gmMJERVDYtbZB5VBgDSl2XBlFvi87SNbYteqsXt1uPCvUSgzj/Vr1qbVV2mKbzzFZYsXq'
    '/vOatbPbYLvV8lapVmeFyhbQSqNmbTYb1VpdZ/OFOkjnxUyh8pyVfrtfK9XrrFpj1t5+2QI3sK'
    '8VKg2rVM8wq1IsN7esyk6GgQOrVBs6Ln17VgPrGtWMEPsxHatus71SrbiLx8KmVbYaz4XAbatR'
    'IWHb1ZrOCmy/UGtYxWa5UGP7zdp+FRdJsmzLqhfLBWuvtIWuvgKZrPS0VGmw+m6hXD5tqM6qzy'
    'qlGmkfN5NtlqBlYbNcIlHCzi2rVio2yKDxqAjnQcEyrgr1/VLRwgj+KMGcQu15RjGtl37TxCpM'
    'sq3CXmEH1i1/ySvYmGKzVtojreGKenOz3rAazUaJ7VSrW8LZ9VLtKS7P9cesXK0LhzXrJSiyVW'
    'gUhGjwgLswj/Fms24Jx1mVRqlWa+43rGoljV1+Bs9AywJot4SHqxWylmKlVK09J7bkB7EDGfZs'
    'twS8Rk4V3iqQG+rwWrERXwaBcCJMGtvJKqWdsrVTqhRLNF0lNs+seimNDbPqtMASghEDENoUVt'
    'NGQS9djmOhmxH7yaxtVth6apHmajUioG6pcBFuK+4qn6t3C0z0Wqi14hrymMDkohoTuoDRtwL9'
    'Vo0J/R6jTYFeVGNCFzHKCFRTY0LvYJQTaDim0RJG8wLV1ZjQZYy+E+j3avyvt8Rd950qgXP/fA'
    'tRHlVfkShRqlxq99jAQ8WL7i+O2+EDZBFMUsKx3ROJv/NcZDGkBPRJmLaHmTEX5BSbLhOiJRBp'
    'tDu02+NiEU5QLaD+QDzHbqUkvNkostLAax8KcThv4ubEXSoxVAgpHYtEivrd4wNkcrYz5AceEq'
    '7LikondnzogAN/i5zVkfeu8aJQcZ217PYbZL2O6PtOOOhg3FmRtu+P+iTVRn3HYITbnKioD/J6'
    'ZFLPcw9w9zNB3eP2YGwq1s37fbDmnXlkWVlzXS++CinYbvXEazCXcxJJr3NE9zGgcioqBauJPg'
    'RrZNbO5/MrWfHbyOc3xO8LsuIRfrIrq9m1lcbq2sb9R/g1H4U/L1BwNk/I4agb2BdypVJJvL1C'
    'I8FhN73aleixvJ1CyyM+RK/g6WpXvT5jte0iW1tbe0TdEl0d6baLxpXVOWcvw7bn+PjYdHjQNb'
    '3hQW7YbdMfIjKDt8FPy3/JqjRVmgVWeouApRuyHg7Zygb6sf4AGxILaaEbzq31W/aaImg5/dpU'
    'Hcx4UdRLPpYz4y7Y58ErtXnLgrzSLJfT6U+uEzG8nMfkWKfVL+l0wAPi4nU79klMN7gPtVkIOM'
    'LVJDhSEk8tvxMcZZhQ6PEvNenIDI7o6c9ZJBehk2ijNVlBpJ2ycO2zFj5z3LVV9nqHB/UTHzdF'
    'mi74206PN05vxLZVLjVQTlk3UGp8juZONwg1baLUPFiHwu03Pvsrtry8LJF0NzA7x7vo7LYQh0'
    'SVZj/8wNZW0+xvmJgre8fhVOi3XA55EPp2vGNfsKSTBVNjeck3owVc5KOVBx8fuYgbka88WF9f'
    'f7j2AGzC89/iOMucNV3nbcjl0cP8WS7mL9vMZWk/XCGdkhObRT9pXGZi6nwhgokPuSvksxjjIw'
    'IgfSoA1j8bAE/sI5u9lhtptkfDIWoCLdlzemizYwFA6RK5lFBs5ecJ/kyYgy5CTZcfb46cHhrb'
    '5TQZVlceUiKkY9KSF/3Qmoq0HXmWLFcrpenKbOGBtNkizkKXsQ/uf9YHyoqwiLL9EzTUbmj4J9'
    'VfTp/dGxyH4tgbmKcM+KSOXmrPHgyQZwFYrkTk1TQjilzMT7j/nq5iqPAyR6sbjM5ehhn8L0zE'
    'ShS9t7SpRGYkG4mSsPn3VEQ/ZN/3cTM5xL9IWh8a73GhGH7YeI/aib8RvB9emu+pMaBA/vDTi3'
    'kd5ZpehEpqYmT3ju0TKP+WGgs/qvtdMMIF6gC3H6rw2AclKcOEKHSrUhieSVpGVCshUlTid3zo'
    'ZQd2pyPvSMGxF3LjdvtQvI+NOha7F1X3jGonqBQeeGw0EIU2JF0WVV+CK5/ua9JQjOR7A8lZSp'
    'p/gY4A136kBuQZuqxz2apQHFCbxZbn0Q3Npx+fQnVyEL0nctBTmEhj8u2ODAZfXDwdGMp8eKLX'
    'CV1JbxCotVq2/Uhah7VOdFIjTRvg0lXPDVR/dTaUyJH2KVEDG/fLSEwLeokuBl6w2200ZqyF27'
    'CQSbTyZhza4H+kBxahReziXIp6v40OiMuzlmHzq/mVh5QzV+438isba/mNlftmfgXuk9GN1EvP'
    'UdId2D46TLFSyEdj+cR2R/SOYOV+hr5ZPjTVAULCqreHzgDnhxweb3ZsRkWDea3fcSrMnrwoq2'
    'CP9aFwEnWTHfYy8Kx6tS7O2HJ6fKaiNz9m33uHNGOLw8XdbLOe63htP/eMt3JjTXI13sVpcNs8'
    't9PzWnbvVVWo4OdIn1xMyE/i/cyhhyiwwkSTEcdcafSaOjPRRoeD16E96qODMpZTE/opC1++Rs'
    '7oCsqYQVDaHMi8Rqas5npOawj3ind05mHQ7y2IUUiL/Ba+AJF5UcmglwxsafF5drGfXew0Fnc3'
    'Fvc2FuvmYvfFksnKzht+7NCnX0fulNgjXahO4UzcnngdW4Tqkg9d4Zmw0G/LVNVRj6g9Py3Ll3'
    'Eqy/0OlEJ7GmRJq5w9cMR+hKgwJyd1zX3MW9gZCshmdZYmH3ot8QLMVjaiiYfCA3E0cAU64C4f'
    '2vKQhQfMlwk5cj1iU4++Sr4Tnwl+r0WfJX+mbyRz/6Cx2vjuFgY+BFC8Cxdj+9rxxkP/dOfB9u'
    'iFGX1Fp+L1mVuF/qlrxQuo3e4hTI74mQ+YpOI741rs4+SkwKZjiAYk/GgTfsD8WXy0+a/QVs34'
    'Ow1Uqbn/0FjFc7MuP4DnjvjpS6WtrKcv759MviarKMIwoTN02CNkDRGTY2bi1aEf4ISyQxti3L'
    'hMwVoRhv/9wBuhzmPP6AoZ3pvPOlTdyTLqj37Kaddin2CFrT8b1/WrETgpwekYJHxCn+PGUIIg'
    'w7gavub/P79MqZg=')))
_INDEX = {
    f.name: {
      'descriptor': f,
      'services': {s.name: s for s in f.service},
    }
    for f in FILE_DESCRIPTOR_SET.file
}


ServiceServiceDescription = {
  'file_descriptor_set': FILE_DESCRIPTOR_SET,
  'file_descriptor': _INDEX[u'isolated.proto']['descriptor'],
  'service_descriptor': _INDEX[u'isolated.proto']['services'][u'Service'],
}
