# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: isolated.proto

import base64
import zlib

from google.protobuf import descriptor_pb2

# Includes description of the isolated.proto and all of its transitive
# dependencies. Includes source code info.
FILE_DESCRIPTOR_SET = descriptor_pb2.FileDescriptorSet()
FILE_DESCRIPTOR_SET.ParseFromString(zlib.decompress(base64.b64decode(
    'eJylWttzE1l6pyVfxMEwjWAGr4dhzpo1lkCW5AswmMmDLMt2s7Lk1QUWqCloSS27d1rdirplYx'
    'gyValKnlL7D2ylkspDHvY9qbzmMVV5yUv+gjyk8hfkMb/v64vaHli2Ni4Dp399znc73/kupxG/'
    'WxBXTNexdM/o5Ycjx3PSqfB54etDxzm0jALjnXG/4JkDw/X0wdCfuvhbRcw1Pd1zG8afj/EmvS'
    'ZmaKnrzStSyVxaW8j7JPIhiXwrJNEIZqY3hBgZYDn2TMeeT2DdlbXr+UioRvSuEZuXvi6mLXNg'
    'evNJLJhu+A+LVXE5kMcdOrZrpB+LuYGhu+ORMTBsz4VYSYh1Y0KepzdtfegeOV7jzOTF/0gE5M'
    'L36bsiwUQ+pRtmpefF7HhoOXrPZaWSjfAxfVtcDoavOqewAeuQbMwF4BZh6ZviYs85sX0CUzxh'
    'AqSXxWfRQ0BkmudciWCfzD1xtevYnm7a7quRv0vu/AxPVcMXwe656ayIsFeW43w/Hrrzszz3sx'
    'Cv+nB6QaQicimeEj3Tu75uWrCjO3/Rfxc+3/1GiMmOpi+JWa32tFTVttULaSFm9rVau1VRlXRK'
    'TO3V2w01kZ4Vye3SczW5tiNSWrBr6U0xzRuT/uLcTgaqLJzf4dAhFi88+fvrIqVOqRfUTVUR/6'
    'Sk5vghvfZ7RZad4enIPDzy5Fpx9RvZOjJktV3WZGnsHTkjNy9LliV5giuhjDE6Bn0h264hnb70'
    'jkxXus541DVk1+kZEo+HzrExso2eHNs9Y4QphiwN9S4RNrsGBMrJp8bIhS3kWr4oMEH3ZFe3Zc'
    'eQfQeLpGnzqqpWrtSaFdk34XFCpFIJdUZNqSqGydQFjGbVjJhLzWAsoM5l6MZPKQXPNO8lPyXw'
    'fk5NqBsLv5RsGOjhjUc2BMeT6Xpm1wXjka8MnXc50u1DQ0IsEiPYYyg0OYsQRw2Jg90cBLsUQx'
    'JA5tT5GJLE8221KL5NTUMcFeJ+rioLeTlxDOk5cuwaLEkTZoat8qG4LAB4ztFq8FPVafUzcYWf'
    'SL2rUO8KuE1HEhFyMYYkgMypl6M1iprGjMvRDCVAUjEkAeSSOhetSajXMONSNIOoEDITQ2jORe'
    'xQuCapXscMEc1IYg0h0zEkASQFaedSU9DlBmzzc97KKdbkBt5dF3+p8CMpu4Dlywsj6cdS8jja'
    'JUvHGCFsdEqGhCu5Q6Nr9k0jcqfQjFLrS9vxJhNyIqTVM/r62ILJQYKWdMejEWiyU8D86VCG1B'
    'RLcUP9AmqE2AxjX8YQBchNdTGGJIEsqXfEcoAoeJ9Qby7ckI0Pe1nIEurz1AV1OSKngCVhczGE'
    'CF5Wb8SQJJAFiPVvoQUTqsSi9MK/KHJff2MOxgNpjwcdHFUc6DOxn+1pGmwO/8yw8X7wrfUDm9'
    '5xBN51yUpwXCAD03VN+zAXGhNjWh83ZS5cEdI/MRFkOoYIF0udN/VU6iOD96rrDIZjMs6p4cWs'
    'koBVSJmb6s1I40RqmrHZGKIASbG3h0gSiKpeZS9TcDIvqMuBzyn8nFI/F3+r8CP53B0QvLvwNw'
    'rbJwgZbmgl+NfIQMzD4e0ejRzbsZxDs6tbMAgCINTJU1iFJkGQO3IswxWhW1og95hGI2PZlTrM'
    'ZumnmIY4YJy3E5mjOzI4xgvWRgnc8U5wykJkBsgljkAhogD5mboUQ5JAMmpWbAKBen56WMid84'
    'EwC0rXD0qxqMkRaYrte5ctdoWfyGD3IM9t3qdEICEhdwPPTAQy3osOTCKQ8R728lYMSQL5OY5Q'
    'SFlRV7DmekSZzgUh98BNjbBpxmZjCK1LIWZOkCSQtHotopxQ83S+IsrkW4SsgJsaYdOMzcYQBQ'
    'jpPkGSQObVn0WUk2oBa76IKCdBmZA8uKkRNs3YbAxRgKTgoxOEKF2P2XlKLZL3R5SnAqQQBCYf'
    'm2ZsNoYoQFKxvZgC5SJHiWaATKvrWHNroSxrUWwoRK4Qlj1SR7b2HA++PgkhpmcMXEm1FNUAw+'
    'C4MlGIR2SLwXH1MZ/VbAxRgKRgwAmSBHJT/SpSfEbdwJqvIsozoEzIesx5ZkB54wzlGVDeAOX5'
    'GJIE8iXkeRwgs+pDrPl84Z5sndMrUpqimW51xxQG5a8OmhMFZyEGLd+AaGqETTM2G0MUIFSgTJ'
    'AkkGvwtJUASamPWIyvYva3HXtlrViMBIlZNgXGtOBhzBFTYPzoDOMUGD86wzgFxo+IcWeGS/p1'
    '8V8F8akeKP3ZuS5g8bG4GDUC1AS4Blyl53cNaAKCR2pgbN12/OYADQw/bP2FuIbwfr6z2LoSUT'
    'wg6EB5ce/Q9I7GnTxmFw5R6dqHExGH3unQcCeS/q+i/EMiuXuw9fvErV2f8kHYszwzLOuXNnqG'
    'Fq158j8r4qJ6C9HvrxWkgH+fQ3V8i6vjf52TvKbrWHJr3O8jwssV6VNDqO7pno4g7hmj7hHXi4'
    'jYA90TZ0rq4jfBAqnZ3bz8SDV95HlDd7NQ6CGNWM4QjEJzkK7DQIiVji9EQQiUCz3E4JHZ8WtH'
    'OodUPCKnBNU4IR3T1lEPkVxuDknWO6IcTf86Y8g5cHqof7o6UchxbgFntJSUZ8Hz2OxhwNU55a'
    'm+Y1nOCSVn2kyTFnFCAh3D24RI9HP3nGAu+W28PxiMUWahltCD7Kd30C3gVWAxQdkeSSbnF+OU'
    'G4lCnCNFnDPigF/X0rHxo/zHhACzmC1CIaBjbwzBIjnERJD/lxxRbu853TH11Xq4SQXY36FcL+'
    'EpqA10y52YmjcIL4WMSx8pVTNMXkmEbX3A/Vfct2xn8s71A7ErOH0zKTRzYEqVBXkKhW2UFT2H'
    'qhYshBADB+HMtwm8kyoXOKfs44UI+7y+d0JuEnhQWEF3scokxxqR79i+F7muX8DK1p7WlM36Tu'
    'tZqVGRGB806k+17cq23HqOlxVZrh88b2i7ey25V69uVxpNWaptA621GtpWu1VvNIVcLDWxdJHf'
    'lGrPZeXXB41KsynrDantH1Q1UAP5RqnW0irNnNRq5Wp7W6vt5iQoyFq9JdBN7mstzGvVc8z2p+'
    'tkfUfuVxrlPTyWtrSq1nrODHe0Vo2Y7dQbQpbkQanR0srtaqkhD9qNgzo6VNJsW2uWqyVtv7KN'
    'IrkGnrLytFJryeZeqVo9q6iQ9We1SoOkj6sptyqQsrRVrRAr1nNba1TKLVJoMirDeBCwiraleV'
    'ApaxjBHhWoU2o8zwVEm5VftTELL+V2ab+0C+0yn7IKNqbcblT2SWqYotneara0VrtVkbv1+jYb'
    'u1lpPEVX3nwsq/UmG6zdrECQ7VKrxKxBA+bCe4y32k2NDafVWpVGo33Q0uq1LHb5GSwDKUtYu8'
    '0WrtdIW/KVSr3xnMiSHXgHcvLZXgV4g4zK1iqRGZqwWrkVnwaGMCJUmugpa5XdqrZbqZUr9LpO'
    'ZJ5pzUoWG6Y1aYLGjOEDYNpmrWmjIJfwxzHXzfF+Sm1HlrafaiR5MBse0NQCd2GzlfcCmweXFp'
    'JrLeRadRF55TGBqaVgTCh1H18z+nUwJvQXGG0xeikYE7qEUY5RJRgTegejAqPhmEbLGC0yKoIx'
    'oRnqrxn9RTD+5y+58X4bpMCFf/wSXh5lXw6USFU2lXty6CDjcXijexLT7hlDRBHu/voIcKc+/t'
    'axEcUQElAn4bU+yk2oIKbo1ExwScBhtD/Su5NkEb6gXED1AT/HmmJi3m6VZWXodI/8zlxqfA1g'
    '2JRiKBFyz0mBFPnbMoaI5HJ3ZBw6CLi2LAcyyZMjExSMN4hZPf8SYTIpFFzIjt79HlGvx3XfqY'
    'F1UO48S911xwNuXJHfMUCv6ndrD4oiUslyqC0281htGfpwoirmLboDkDZ6i4iyfs61nfgshGC9'
    'Y/H9mm0YxJLuibj6GFI65UwhG1yHYI4ftYvF4uoK/7aKxU3+fUFaPMLPyurayvpqa2198/4j/O'
    'YfhT8vkHC2TsngyBvdsH1nkfhaDIWEAb3pythHT/zGFlKiB0at4IhgV52BlI2dslxfX39E1RK1'
    'jtQOo3CVTcOQL8Oy5+TkJG8aXj/vjA4Lo36X/tCivPfG+y7zx8zKUqa5LStv4LDUXItwKFc3UY'
    '/x5UHMpVk2nFvt1/I1eVAm+zofVDCTSVEt+dh/M6mCXcN7FWxehpfX2tVqNvvBeezDmSJeTmRa'
    '+5RMh4ZHVJx+Tz+NyQbzITczg2O0Jt5xwPHM9DvecU6yQI//VJWO894xPf0hjfxJqCS6KE1W4W'
    'lnNFz/qIbPTHt9Tb7eNbzmqYtOkV6X3B3TMlpnN2JHq1ZaSKey7wVifGzNnb4XStpGqnmwAYG7'
    '37vyz2Qmk/GRbN/L9072UNltww9pVVZ++61cX8vKHyS/qzon4avQboUC4iDk7TknLpOkkwVVY3'
    'HJzUcTDI5Hqw9+euQiarR89cHGxsbD9QcgE57/4K6nbZtvQiqPHhbPU8n/aZuZ8fWHKXyjFHiz'
    '6CeLZiYmzic8mOiQuUI6SzE67ADZMw6w8VEHeKIf6/K1v5H54FaQpuybFsrsmANQuEQsJRRb+f'
    'EFf8DNsS5C87ZxsjU2LRS2mSwp1gwsFLDwDZP1adEPzan5uiPOkubBTF/1QG22QDbfIcosy8QG'
    '9z9qg/hlKOWzg1MU1Hao+AfFz2TP7w2OQ3liDbynCPikiVpqXx8OEWcBaLaP+K1pjpNczE7of8'
    '9mMWR4P0YHHYyQL8MI/kcG4oAVXXnqlCJzPhkfJWaL7yiJvl95N0BncoR/EbTet96hoRi933yH'
    '3Im/4bzvX+bfUWFAjvz+uxeLAuma7lD91URIt070Uwj/hgoLN8r7fRBCA3WI7ocyPPYh4JSTzA'
    'rVqs8Mz8Qtx9mKWXImfmuMnJWh3uv5PZJ34oTUDL17xFe5UcWiW1F2zwXlBKXCQ0eOh5xow6UZ'
    'zvo+uPrhuiYLwYi/M/Qp+5wWX6AiQNuP0IA4Q8264Zcq5AdUZsnMIqqhxezjM6ggA9E9kYmaIo'
    '8w5t/u+M7gcuNpQlHpwhJWLzQl3SBQaZXR3YhbT3ZOBYmRpQ2wqdWzvaC+Ou9KZEj9DKuhjv4y'
    'YkM3/FzFwAp6t4vCTHbQDTNPWut3xqEO7k/kwCSUiH2cS873O6iADP+s5eTiWnH1IcXM1fut4u'
    'rmenFz9X6+uArz+d6N0EvPUdAd6i4qTJ7J/FFYPtHtMd0RrN7P0cfQh/ngACFgNbsjc4jzQwaP'
    'Fzu6pKQhnc5vDErMjt8oB84eq0NhJKome/Kl52jNepPPWCY7OVPRzU9+4LxFmNH5cBn2SrtZ6D'
    'ldt/DM6BQmkhQaRh+nwe4ahV3L6ejWqzqL4BZInkKMyXd8P3PkwAu0MNDk+JgHEr2myozL6HDw'
    'OtQn+F4RKGtQEfohDV++Rszo88qYQhA6P/TjGqmyVrDMzgjm5Tu6/JE3sG7zKFyL+BZegPhxMe'
    'BBlwxyeen5ytJgZanXWtrbXNrfXGrml/ovlvOyan5vnJj0Tdn0d4r3SLDo5M5E7YnT09lVl13I'
    'CsuEiX7HD1W94BG557uMfxkXRLnfYCVLT4MVkqqgD03ejxBldQq+rIWf0mY9QwYrK0JmyYZOhy'
    '/A9EBHFPEQeMhHAy3QoWEbI90/ZOEBc/2AHJkevimiT6Rv+TPB300+kf5I30gWfqvIxqR3Cx0f'
    'DMjf2cTYvm688BAfrjzkPl2Y0ed5Sl4f6SrEh9qKFxC7a8FNjs9/PyUR36rXYt9GpxmbjSEKkP'
    'CjTfj99Ef+aPPfoa6K+lcKf838T0XWHHvFNg5huWPjbFOpB9rTJ/0PBt+8rAULw4AuUWGP+dMk'
    'fHJCjK8OXY++Vx7pxwbfyUc8mXSwMPx/Dc4YeR57Ri1k2DefN2jQk+WCP+KM0a7FvgCzrj+q18'
    'XVCJz2wdkYxDahz50TKEmQql4Nr/n/D+xK7VQ=')))
_INDEX = {
    f.name: {
      'descriptor': f,
      'services': {s.name: s for s in f.service},
    }
    for f in FILE_DESCRIPTOR_SET.file
}


IsolatedServiceDescription = {
  'file_descriptor_set': FILE_DESCRIPTOR_SET,
  'file_descriptor': _INDEX[u'isolated.proto']['descriptor'],
  'service_descriptor': _INDEX[u'isolated.proto']['services'][u'Isolated'],
}
