# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isolated.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='isolated.proto',
  package='isolated',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eisolated.proto\x12\x08isolated\x1a\x1fgoogle/protobuf/timestamp.proto\"t\n\x0cStatsRequest\x12*\n\x06latest\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12(\n\nresolution\x18\x02 \x01(\x0e\x32\x14.isolated.Resolution\x12\x0e\n\x06number\x18\x03 \x01(\x05\"b\n\rStatsResponse\x12*\n\x06latest\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12%\n\x0cmeasurements\x18\x02 \x03(\x0b\x32\x0f.isolated.Stats\"\xdc\x01\n\x05Stats\x12&\n\x02ts\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07uploads\x18\x02 \x01(\x03\x12\x15\n\ruploads_bytes\x18\x03 \x01(\x03\x12\x11\n\tdownloads\x18\x04 \x01(\x03\x12\x17\n\x0f\x64ownloads_bytes\x18\x05 \x01(\x03\x12\x19\n\x11\x63ontains_requests\x18\x06 \x01(\x03\x12\x18\n\x10\x63ontains_lookups\x18\x07 \x01(\x03\x12\x10\n\x08requests\x18\x08 \x01(\x03\x12\x10\n\x08\x66\x61ilures\x18\t \x01(\x03*B\n\nResolution\x12\x0b\n\x07INVALID\x10\x00\x12\n\n\x06MINUTE\x10\x01\x12\x08\n\x04HOUR\x10\x02\x12\x07\n\x03\x44\x41Y\x10\x03\x12\x08\n\x04WEEK\x10\x04\x32\x45\n\x07Service\x12:\n\x05Stats\x12\x16.isolated.StatsRequest\x1a\x17.isolated.StatsResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_RESOLUTION = _descriptor.EnumDescriptor(
  name='Resolution',
  full_name='isolated.Resolution',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MINUTE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOUR', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DAY', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEEK', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=502,
  serialized_end=568,
)
_sym_db.RegisterEnumDescriptor(_RESOLUTION)

Resolution = enum_type_wrapper.EnumTypeWrapper(_RESOLUTION)
INVALID = 0
MINUTE = 1
HOUR = 2
DAY = 3
WEEK = 4



_STATSREQUEST = _descriptor.Descriptor(
  name='StatsRequest',
  full_name='isolated.StatsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latest', full_name='isolated.StatsRequest.latest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resolution', full_name='isolated.StatsRequest.resolution', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='isolated.StatsRequest.number', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=177,
)


_STATSRESPONSE = _descriptor.Descriptor(
  name='StatsResponse',
  full_name='isolated.StatsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latest', full_name='isolated.StatsResponse.latest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='measurements', full_name='isolated.StatsResponse.measurements', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=277,
)


_STATS = _descriptor.Descriptor(
  name='Stats',
  full_name='isolated.Stats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='isolated.Stats.ts', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uploads', full_name='isolated.Stats.uploads', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uploads_bytes', full_name='isolated.Stats.uploads_bytes', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='downloads', full_name='isolated.Stats.downloads', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='downloads_bytes', full_name='isolated.Stats.downloads_bytes', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contains_requests', full_name='isolated.Stats.contains_requests', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contains_lookups', full_name='isolated.Stats.contains_lookups', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requests', full_name='isolated.Stats.requests', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failures', full_name='isolated.Stats.failures', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=500,
)

_STATSREQUEST.fields_by_name['latest'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STATSREQUEST.fields_by_name['resolution'].enum_type = _RESOLUTION
_STATSRESPONSE.fields_by_name['latest'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STATSRESPONSE.fields_by_name['measurements'].message_type = _STATS
_STATS.fields_by_name['ts'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['StatsRequest'] = _STATSREQUEST
DESCRIPTOR.message_types_by_name['StatsResponse'] = _STATSRESPONSE
DESCRIPTOR.message_types_by_name['Stats'] = _STATS
DESCRIPTOR.enum_types_by_name['Resolution'] = _RESOLUTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StatsRequest = _reflection.GeneratedProtocolMessageType('StatsRequest', (_message.Message,), dict(
  DESCRIPTOR = _STATSREQUEST,
  __module__ = 'isolated_pb2'
  # @@protoc_insertion_point(class_scope:isolated.StatsRequest)
  ))
_sym_db.RegisterMessage(StatsRequest)

StatsResponse = _reflection.GeneratedProtocolMessageType('StatsResponse', (_message.Message,), dict(
  DESCRIPTOR = _STATSRESPONSE,
  __module__ = 'isolated_pb2'
  # @@protoc_insertion_point(class_scope:isolated.StatsResponse)
  ))
_sym_db.RegisterMessage(StatsResponse)

Stats = _reflection.GeneratedProtocolMessageType('Stats', (_message.Message,), dict(
  DESCRIPTOR = _STATS,
  __module__ = 'isolated_pb2'
  # @@protoc_insertion_point(class_scope:isolated.Stats)
  ))
_sym_db.RegisterMessage(Stats)



_SERVICE = _descriptor.ServiceDescriptor(
  name='Service',
  full_name='isolated.Service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=570,
  serialized_end=639,
  methods=[
  _descriptor.MethodDescriptor(
    name='Stats',
    full_name='isolated.Service.Stats',
    index=0,
    containing_service=None,
    input_type=_STATSREQUEST,
    output_type=_STATSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICE)

DESCRIPTOR.services_by_name['Service'] = _SERVICE

# @@protoc_insertion_point(module_scope)
