# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: isolated.proto

import base64
import zlib

from google.protobuf import descriptor_pb2

# Includes description of the isolated.proto and all of its transitive
# dependencies. Includes source code info.
FILE_DESCRIPTOR_SET = descriptor_pb2.FileDescriptorSet()
FILE_DESCRIPTOR_SET.ParseFromString(zlib.decompress(base64.b64decode(
    'eJztW0tsG0l6NkVLotqPadOeGY3s9dTSI1u0KZKS/FhL9gCURMn0SqSWpMZrGwO7RTalXlPd3O'
    '6mZNnjTC7Z0yKHADkGQYIghz3kECC55xoEOeSQSw655BDkHiDHfP9f1Q/qMfZsLjnYkO3uv6r+'
    'V/31v6ql/e0V7bzlOV3DN9v5nuv4TjoVvE9c3Xac7a5ZYPhWv1No913Dtxxbzpz48vC4b+2anm'
    '/s9uSEzJ8mtLMN3/C9uvnrPkbSs9oIofb88YRITJ2ZnchLFPkARb4ZoKirmenbmuaaYKlPlMeH'
    'sO787KV8yHQ9HKvH5qUva2M9Y9t84VlvzPEkFg3XUwRo4D2zpp1TbHk9x/bM9IJ2dtc0vL5r7p'
    'q274G7JLj7PKLC0xu20fN2HL8+MDnzh0mFLhhP39SGGMn7RMSs9LR22usZ9rjGs784MntZ6bzO'
    '09Lj2mi/13WMtseqSNaD1/Q17Zx6fLF1AM2x1Mn6WQVcJFj6ijbWdvZtieA0T4gA6RvaJ+GLQj'
    'LMc86HYInmlnah5di+YdneC1furTc+wlP1YEDtuZfOaiHsRddxXvV73vgoz/0kgK9JcHpCS4Xo'
    'UjwlfKexjmF1oXZvfEyOBe83VzUtsgPM/KxebtTWNpuVWvXFZrWxUV6qrFTKy/qptKaNrFeqm8'
    '2ynkintNOPapt1fSg9qiWXS0/15OyKlqqoPU/Pa8O8renPDtmBkmzisH0E5pQ59fhfPtVS+mn9'
    'lP5QT2h/l0id5Zf07O8SYsnpHbjW9o4vZoszPxPNHVOsbS5VRKnv7ziulxelblfwBE9ANtPdA3'
    '5NbHqmcDrC37E84Tl9t2WKltM2BV63nT3Ttc226Ntt08UUU5R6RosQWy0TDOXEN6brQTViNl/U'
    'MMHwRcuwxZYpOg4WCcvmVWuVpXK1URYdCxaoaanUkD6ip3Qdj8nUKTyN6jf4OaGP4XlKO5saAf'
    'wMRDsPOfkNY2d4zXN+G8L4OX1Ivz3xc8FKgkx+37UhBN4sz7daHphwpWDkQIRr2NumAIvEktp+'
    'CBcdbrCmB8hB7hyYPBODDAFyVh+PQZKAXNOL2oPUMNi5AHY/0xMTeRHZjPAd0fdM5qQBlUNv+Y'
    'BdZgA0z9Jq0LugD+ufaOf5jcRLQ7yfgNpwyBFBxmOQIUAu61fCNQn9ImacC2ckFCQVgwwBckY/'
    'G64Z0i9hxplwBmEhyEgMQnPGsFvBmqT+KWZo4QzaOIIMxyBDgKT0MUh3GrKMQzc/5a08zZKMY+'
    'yS9m8JfiVhr2D5jYl/TAjpncn8aJu6Bp7hDd0D0iTsyuuZLatjmaFtBXoUlY6wHT+akNMCXG2z'
    'Y/S70DlQ0JJW33WBk62C130nJ37HVB0HOFs0Lv/TmL5lemLfwgkCD7uW51n2tjCYxwNhuCaTPj'
    'Bh/s5ur08nV9PSgXCp0yzeuP4Z9BPARhh2OQZJAHJFz8QgSbxP6te1GwqS0K9izZWJz0X9ePMN'
    'SEKvcirOlR7CRhh2NgYhhOf0z2OQJCATYGtZQYZ0gTWfTdwW68Zra7e/K+z+7ha8AXzGQHAKte'
    'Q76ijG+BkCP4TnKoxVD2HDDBuNQRKApPQLMUgSkEv6p2w4CRy2U/oNZUYJfk9h7M8S/EpmdB0I'
    'b078NsG8KS/gBRzCYlwTLg3nsbXjOrbTdbatltEVjgv/hh3Nk9fEZioftuN0TU8LDK0LdAv05J'
    'o3PGHAqrrGAabhaJuBxQQ6IItouaYhDUEP2IMWrquDE0BGADnDhzqAJAD5Qp+MQZKATOlZrQYI'
    'xJPef6J0SP9BzBOe9DOHHaEB+7URb9nbk+VrrEZS+k1W4zK/kRZzYPIatjzMKKRrd80eBQ7bl2'
    'cTI64vY4epcKstH1LCEp6byryGlLi50OqHlLg5mOnVGCQJyE9xDhYUJKHnsWZy4pYIcpZBopGb'
    'D3Y6xgadBFqe06+FJOgkEGwiBiEil/UvY5AkIBn9Kzi908oJFrHmUoiZbJogebVXQ8qmi6FNDy'
    'n2i1DvJzFIEpC0fjHEnNRnmJsAcxKYCVIENT2EDTNsNAZJAEIbF0EI07j+RYj5tD5LpzfEfFpB'
    'ZmKynwbm2QHMdNJmw3MoIUlA6BwGmIf1OfIvIeZhYCbIrHJyEiZnjcYgCUBSMZMYBuY59jgNBR'
    'nR75KnmFgS1dDTFELjDtI2YSC98B0fpzdySJZv7nqCckFKWnoxMxgBe4R2TjkgCRtm2GgMkgAk'
    'BQVGkCQgVxCHA8FH9XsclwPMo8BMkLsxGx4F5nsDmEeB+R4wj8cgSUAoej9QkJQ+jzWfTuRE85'
    'BcodDwrfBXrT7FK/GLjUZMwhT4oPX3OGcIYMMMG41BEoBQGhVBkoBchKlNK8iY/oD5+ElsA2zH'
    'np4tFkNOYoTHQJgWzMcscQyEHwwQHgPhBwOEx0D4ARHeGuGiZE77q+vae0rD9CeHypjMvJYKvA'
    'LVMJ4JS2nLGgk1jHpNX9KGbcN2ZG0zXJcvi99pFxGuD1dGi+cChBsE2Ug8u7lt+Tv9rTwmF7aR'
    'mNvbEX89/6BneiGb/5NI/OVQcnVj8XdDV1cl3o2g4npidrs/t1HwNGnJ47/5Cqn8VThzHwHtn8'
    '4ilb/Kqfw/nBW8pOV0xWK/00G8EtNCIkPgaRu+gZDkm25rhxNaeL9dA1lKPP8v/kwtEBW7lRcn'
    'pP47vt/z5guFNoJi1+mBUKALkrSnmJjekkwUNA1pRxsRxbW2ZHJLZ5CyW0RIVToQZMuyDeRrxJ'
    'eXg4/2dxBg+X+nDz53nTbysxarK8eREpR3LZ+SGdDcs9p44HhDLr7jdLvOPmVbtJMWLeLwCjym'
    'Pw+W6M/NQ4x5ZLLxYma371H4IhfCWI0tlDYYUhrTKH1DyMzJMEKRnjDEKZK3GWAH9FpdAwHSzZ'
    '/EBIjFdBEwARnbfTAW8qFFjPyf+AgzlbbT6lMLwQg2qQD9O5S5CFgKMh2j60Wq5g3CoCbi3IdC'
    'VU2LVxJi29jlYjFuW7YTjXnSCXsaJyOMCpUniFKeRJZCLhtJUtuhHAwLwcSuA1cmdQLrpDwMxi'
    'k6GNCCorTj75OZKAsKMvwWVllkWC7Zji2tyPNkIiyajyoN0aitNJ+U6mWB54167ZvKcnlZLD7F'
    'YFks1Tae1iurj5riUW1tuVxviFJ1GdBqs15Z3GzW6g1NZEoNLM3wSKn6VJR/uVEvNxqiVheV9Y'
    '01VP4C6OularNSbuREpbq0trlcqa7mBDCIaq2pofRdrzQxr1nLMdmj60RtRayX60uP8FparKxV'
    'mk+Z4EqlWSViK7W6Jkpio1RvVpY210p1sbFZ36ihnCbJliuNpbVSZb28jEqmCpqi/E252hSNR6'
    'W1tUFBNVF7Ui3Xifu4mGKxDC5Li2tlIsVyLlfq5aUmCRQ9LUF5YHANZRX3PfAEfZQhTqn+NKeQ'
    'Nsq/2MQsDIrl0nppFdJNvU8r2JilzXp5nbiGKhqbi41mpbnZLIvVWm2Zld0o17+pLJUbC2Kt1m'
    'CFbTbKYGS51CwxaeCAujCO58XNRoUVV6k2y/X65gZ1a7LY5SfQDLgsYe0ya7hWJWnJVsq1+lNC'
    'S3rgHciJJ4/KgNdJqaytEqmhAa0tNePTQBBKhEiRnKJaXl2rrJarS2UarhGaJ5VGOYsNqzRoQo'
    'UJwwZAdJOlpo0CX5p8jplujvdTVFZEafmbCnGuZsMCGhVlLqy2pUdK56rDIjjPQnxHFntKXyBg'
    'alI9E5RqqS8Z+qV6JuhXeCox9Ix6JugknnIMTahngl7HExMLn+npBp4yDNXUM0GnqAHA0K/U81'
    '9wkad3ZASc+BMdRh4m+LFSwxCetW2jnhcd67XZnu6a9jY8FnUtg1Immm62NSrLDTigvs3OU6UA'
    '7Dk7rtGK4kMwAK9L6QC/avF6WlS4D4Eiw+zBaZkSoWEfUBIGgOEyVqxrmT2f/PUrU2TaxkFGI+'
    'eW2YUT3MkEaFyTW3rkAaO6ij22CnUIi4izJpDBW/r7pmnDA+7HZ+8ZXWRfhMyIVEUsWGHfzWiT'
    'Twd1r7/lk7ikEfKmWBIiyos6pw6EqAffi8IerHUPxK3pmWKuiDzvwDRcSvLENVF+jRVUCGvBo5'
    'iZR7bBfY6IDaYxwC4HwJ5n9tsOR+G8itaRPLKCfCjy+fzC4THod2AkJBSkWsGoHA7zxGBbHxKG'
    '8G1a0greFw4tYgNQS+RzsIDfAiJWR0wdIfRAFMX164dxfS2KWfFWLjuGu1sPxczCkVFFGmPF4I'
    '+a9E6YXUq0Ygx4IbKvj+XgwQ9zMP0DHNw6joPY/s9G+x9tGBtA9Bqr1n+8GZy42ScbiRyK7/nD'
    'wT0HR4eVsBAtCiwgtuvxBUfMIFozqOcBo4urOFpwrHaj/Y0mfh2feAKNW8fTONaGYjs4d9IJRn'
    'lhcneI/mmbXS42xMYBUi872DmflH504hQ8n/dwLid2LRuIvYczxezgOcOygNrUoaH8Cqg3Q1R+'
    'O8vO53EDQXodTgqpLgAVW0JkzZNjtxnyT5UYuTR4UIecIMcBymiRJWOKTGINcphwz1u/MltAsM'
    '/9PtnN4okmKVXl0R4KH+u1yHgZMYUgwDULpijVZ8nzakSwR90/orh1IFPhsGxWU1UVFIUZMPma'
    'IpbHbGphYELVrybkxQqcuCm3KyfmwnDFmIoDuDykxV1QN7VQdmtAUaSKzJyXIXkt2v2BqDgTQ6'
    'ZwaRRKIhaPw5YPrGuG8BKeQ1hRoVktdxDvh6IFThibFl4XdLhz8O/RdcErasVN/HNCNDg3CCmr'
    'xmA8OciLdSq86E6KDHx6buZO7s69uxTm6K9GAfnWISBYa3X7HkqRvKiiQJknrDifW3Srpdq7qt'
    'HPWOc1cbdITBRg+yia8IKHwo6L59nbYsct4Gzgee7unfzsHUEHpUAhFiA+pjLeDl4ZkIgdPR27'
    'Dhhm2GgMkgAk6C0GVwavuLf4m2R4Z+BhUXriv4cCXQ1kQYZS3WAaFMuC4irVIp0Gpw5ZDzZTHi'
    'zHNkNs7kBSJq3WEND2S7VVL5HOmbAIshVD9BwPFe4eF4W2uW3w80tmSE2UByIMfsxKjCDGdh0X'
    'J8XgXtUb03VkuqS6w4ewyWKcTkwgHpW2lGiqW53DfB62ovv37+fUX2lBMUDMegavZGgnXqmmro'
    'QNM2w0BqH9SvEdXnQl4+m6fiFsk/1HQXvfFxJH+2QL2lgYNn90o+wPjm+UnQ8xBp2yW+/vlIWc'
    '/ohW2X9Na2PcHftN4mOv7GOv7GOv7GOv7GOv7GOv7P9Dr2wx1itbfE+vrBDrlRV+VK/s7y9zr+'
    'yNCoETf30ZVh6VwQPdsp6DiMfujTpjxzSvGP4GuRN3qYJWVm4gXzO8D2mcaSekjCC+2VwS5Z7T'
    '2gm+svHjpVmfv59hR4r43TV78ORi1TW3HThcWywF7TWUK8Bgvva5LCPXGU0KGEetYrReweu1+X'
    '6U02oId5ik4Xn9Xf5qB/FdVagcUe8iKQ1E6jr2dk5YeazumkYvEhXzMt4uUJvtDLysjLm2E58F'
    'F2xsdbkCtU0uBynz5OyjR+FUthTDxpv02lTrTPNPs1ic559nJAWyyPvTM7MoVpqzc/N37uMnfz'
    '/48wwBZ/GAFI640eKa1Fcs8TduSCRQZtn0JamE7stPWsDlnukiV3A0tavIZEV9ZUnMzc3d54pe'
    'lcEeKDRMUzwP0p79/f28ZfqdvONuF9xOi/7Sorz/2v926kNmZT+km3iom4RzW/mleEkWNJV9eb'
    'RxFOaSqsMRZcGe6b9QmzfFy6uba2vZ7LHz2IanitmFD+pwKZ62TZ+wOB3UcjHeoD7EZiaA6kP4'
    'e4riwPTr/l5OMEMLv69Ie3l/j95+SCI5CZlES5WZAxLOnSjhE8uemxUvV02/ceD5JndlSt6K1T'
    'WbgxuxUlkrNxFORcdXbJy05nrHDzjdRKi5exsMt15Rv21qakpCsh0/395/hMxuGXZIq7LiwQMx'
    'N5sV3wkeW3P2g6FAb4UC/OAT/grIY5R0siBqvD2SDyeY7I9m7h49ciE2Wj5z9/bt2/fm7haL4f'
    'lXX3lt2tbrAMv9e8XDWPK/32ZOSfmhCqmUQti6y6KYibHzHgsmPKSuAM9kDA8bQHbAAG6faACP'
    'jT1DvJQbmVcfS9KUdauLNDtmAOQu4UsJiq08ecEPmDnWRdcStrm/2Le6SGynsiRYQ2lIkZCKyQ'
    'bdTiFoTlXKDj9LkquZUvRs0F4h0fNbhJl5iXRw50QdxL8RPaYDehz7QUsz2hsch6VIG1Mf3NKM'
    '6ekHepqygtHE88CDf6AjVqToY0eDQmROolFdOBDLvKUg+m76LV9g4X84rXfNtygo3HfzbxE78S'
    '+M993z/FtKDMiQ3337LKOpbqpczZdL3X3jIN7rlHG/A0QooLZR/aiGpKKUE0wK2aokhneiJtuL'
    'TJIjMTV3pnvyposC374TYDON1g5/xBnrqGqxLiynExQKtx3R73GgDZZOcdSXwJnj85osGCP6Tk'
    '9ilpQyzzJBp1g1iU2ZqpAdUJolpjLIhjLZhQGoJu8Ef923kFPk4cZkd0cag8eFpwVBg8apUiV1'
    'ECi1mjK8kBr1nTViI0sbYFOpZ/sqvzpsSqrbFiPVM1BfuvEeMmcx0ILRomtNsYVqmGnSWlkZBz'
    'J4R/gQ3Hft4FxyvB/oYWdmizP3yGfO3GkWZ+bnivMzd/LFGahPWjdcL72HTrdneMgweSbTR2L5'
    '2LD71COYuZOj33K4l1cHCA6r0XKtHs4PKTye7BiCgoZq+Ms8yfICY4/loVASZZNt8dx3Ko1ag8'
    '/YVDY6U2HnJ7/rvIGbMfhwmfb0ZqPQdlpe4Ym5VYg4KdRNdZtbWO06W0b3RY1Z8ArETyFG5Fvu'
    'z+w4sIJK4GhyfMwVRy/Du5bg4WUgj7r1VcLSXe+xEj5/CZ/R4ZUxgcB0vif9GokyW+haWy7Uyz'
    '26/I6/273GT8Fa+LegASL9oqJBTQZxY/Lp9OTu9GS7OflofnJ9frKRn+w8u5EXa9Yrc9+iXxax'
    '5E7xHmnMOpkzYXvstOX19A0PvEIzQaBfka6qrV4Re76dks045eV+hZXMPT1ME1cFo2fxfgRQFq'
    'cgeS0cxc1yBgSmpzWRJR06W9wAM5SMSOLBcI+PBkqgbdM2XXkbFHp7dW0Uqn7gAuMNf07759EF'
    'xvd8gfHHCVGParfYJQbZO6sY29eKJx7a8ZnHYHf6hKpCO66seHZst5ouIIjFN/rFgQuI749cQH'
    'x/5ALie76A+M9EeAHxRwm+gfjXhKg69nTY3v9x9xB5UVULA4cefA7BNhkh49ah59PvauwYeyZf'
    'B4Q05e2oXBj8whJ/KYI9oxIyqJsPK1TVZFHLP660i7EWP8v6vX5JuxDr8TNwNAZinVCX/0Ksyw'
    '9QrM3/v2GV6Rg=')))
_INDEX = {
    f.name: {
      'descriptor': f,
      'services': {s.name: s for s in f.service},
    }
    for f in FILE_DESCRIPTOR_SET.file
}


IsolatedServiceDescription = {
  'file_descriptor_set': FILE_DESCRIPTOR_SET,
  'file_descriptor': _INDEX[u'isolated.proto']['descriptor'],
  'service_descriptor': _INDEX[u'isolated.proto']['services'][u'Isolated'],
}
