# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import swarming_pb2 as swarming__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='task.proto',
  package='bot',
  syntax='proto3',
  serialized_options=_b('Z-go.chromium.org/luci/swarming/proto/bot;botpb'),
  serialized_pb=_b('\n\ntask.proto\x12\x03\x62ot\x1a\x0eswarming.proto\"C\n\x0bTaskDetails\x12\x34\n\x0ftask_properties\x18\x01 \x01(\x0b\x32\x1b.swarming.v1.TaskPropertiesB/Z-go.chromium.org/luci/swarming/proto/bot;botpbb\x06proto3')
  ,
  dependencies=[swarming__pb2.DESCRIPTOR,])




_TASKDETAILS = _descriptor.Descriptor(
  name='TaskDetails',
  full_name='bot.TaskDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_properties', full_name='bot.TaskDetails.task_properties', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=102,
)

_TASKDETAILS.fields_by_name['task_properties'].message_type = swarming__pb2._TASKPROPERTIES
DESCRIPTOR.message_types_by_name['TaskDetails'] = _TASKDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskDetails = _reflection.GeneratedProtocolMessageType('TaskDetails', (_message.Message,), dict(
  DESCRIPTOR = _TASKDETAILS,
  __module__ = 'task_pb2'
  # @@protoc_insertion_point(class_scope:bot.TaskDetails)
  ))
_sym_db.RegisterMessage(TaskDetails)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
